// Cloudflare Worker — the Packman leaderboard.
//
// GENERATED by tools/build-packman-worker.py from packman/geom.js,
// packman/levels.js and packman-scores.src.js. Edit those, not this file.
//
// GET  /api/packman?level=<level name>   the ten fastest for one level
// GET  /api/packman?level=all            the ten fastest across all seventeen
// POST /api/packman                      {level, pid, name, t, m, p} one win; p is where every piece ended up
//
// Deploy via the Cloudflare dashboard:
//   1. Storage & databases -> D1 -> Create database (name: packman).
//   2. Workers & Pages -> Create -> Worker (name: packman-scores) -> Edit code -> paste this file -> Deploy.
//   3. That worker -> Settings -> Bindings -> Add -> D1 database: variable name DB, database packman.
//   4. That worker -> Settings -> Domains & Routes -> Add route: www.garvitgupta.com/api/packman*
// The tables make themselves on the first request.
//
// Housekeeping, from the D1 console:
//   SELECT * FROM scores ORDER BY at DESC LIMIT 50;      -- the latest scores
//   DELETE FROM scores WHERE name = 'someone';           -- take a player off the board

// Packman geometry: convex-polygon overlap, containment, and the drop "settle".
// World units: a size-1 square has side 1. Angles are whole degrees, y points down.
var PackmanGeom = (function () {
  'use strict';

  var H = Math.sqrt(3) / 2;
  var SHAPES = {
    square: [[-0.5, -0.5], [0.5, -0.5], [0.5, 0.5], [-0.5, 0.5]],
    triangle: [[0, -2 * H / 3], [0.5, H / 3], [-0.5, H / 3]],   // centroid at the origin
    domino: [[-1, -0.5], [1, -0.5], [1, 0.5], [-1, 0.5]],
    hexagon: [[1, 0], [0.5, H], [-0.5, H], [-1, 0], [-0.5, -H], [0.5, -H]]
  };

  // How much pieces may sink into each other or a wall and still count as packed.
  // Kept tiny on purpose: the last level's container is only ~0.03 tighter than
  // the easy 45-degree packing, so a generous tolerance would let that one through.
  var EPS = 0.002;
  var SNAP = 0.22;      // deepest overlap the settle will push out of
  var MAX_SLIDE = 0.5;  // furthest a settle may move a piece from where it was dropped

  function verts(p) {
    var base = SHAPES[p.type], s = p.size || 1;
    var r = p.angle * Math.PI / 180, c = Math.cos(r), n = Math.sin(r);
    var out = [];
    for (var i = 0; i < base.length; i++) {
      var x = base[i][0] * s, y = base[i][1] * s;
      out.push([p.x + x * c - y * n, p.y + x * n + y * c]);
    }
    return out;
  }

  function normals(poly) {
    var out = [];
    for (var i = 0; i < poly.length; i++) {
      var a = poly[i], b = poly[(i + 1) % poly.length];
      var dx = b[0] - a[0], dy = b[1] - a[1], l = Math.sqrt(dx * dx + dy * dy);
      out.push([dy / l, -dx / l]);
    }
    return out;
  }

  // Separating-axis test. null if apart; otherwise the shallowest way out,
  // as a unit direction to move A plus the distance.
  function overlap(A, B) {
    var best = null, axes = normals(A).concat(normals(B));
    for (var k = 0; k < axes.length; k++) {
      var nx = axes[k][0], ny = axes[k][1];
      var minA = Infinity, maxA = -Infinity, minB = Infinity, maxB = -Infinity, i, d;
      for (i = 0; i < A.length; i++) { d = A[i][0] * nx + A[i][1] * ny; if (d < minA) minA = d; if (d > maxA) maxA = d; }
      for (i = 0; i < B.length; i++) { d = B[i][0] * nx + B[i][1] * ny; if (d < minB) minB = d; if (d > maxB) maxB = d; }
      var fwd = maxB - minA, back = maxA - minB;
      if (fwd <= 0 || back <= 0) return null;
      if (!best || fwd < best.depth) best = { depth: fwd, nx: nx, ny: ny };
      if (back < best.depth) best = { depth: back, nx: -nx, ny: -ny };
    }
    return best;
  }

  // A convex container as half-planes with outward normals: inside is n.p <= d.
  function makeContainer(poly) {
    var cx = 0, cy = 0, i;
    for (i = 0; i < poly.length; i++) { cx += poly[i][0] / poly.length; cy += poly[i][1] / poly.length; }
    var ns = normals(poly), walls = [];
    for (i = 0; i < poly.length; i++) {
      var nx = ns[i][0], ny = ns[i][1], d = poly[i][0] * nx + poly[i][1] * ny;
      if (cx * nx + cy * ny > d) { nx = -nx; ny = -ny; d = -d; }
      walls.push({ nx: nx, ny: ny, d: d });
    }
    return { poly: poly, walls: walls };
  }

  // How far a polygon pokes through one wall (negative when clear of it).
  function excess(A, w) {
    var m = -Infinity;
    for (var i = 0; i < A.length; i++) { var d = A[i][0] * w.nx + A[i][1] * w.ny; if (d > m) m = d; }
    return m - w.d;
  }

  function pointInside(C, x, y) {
    for (var i = 0; i < C.walls.length; i++) {
      var w = C.walls[i];
      if (x * w.nx + y * w.ny > w.d) return false;
    }
    return true;
  }

  // 'in' fully inside, 'out' clear of the container, 'edge' straddling a wall.
  function zone(A, C) {
    var worst = -Infinity;
    for (var i = 0; i < C.walls.length; i++) { var e = excess(A, C.walls[i]); if (e > worst) worst = e; }
    if (worst <= EPS) return 'in';
    var o = overlap(A, C.poly);
    return (!o || o.depth <= EPS) ? 'out' : 'edge';
  }

  // Judge the whole board. Pieces left out in the tray never count as colliding.
  function evaluate(pieces, C) {
    var n = pieces.length, V = [], st = [], i, j, packed = 0;
    for (i = 0; i < n; i++) { V.push(verts(pieces[i])); st.push({ zone: zone(V[i], C), hit: false }); }
    for (i = 0; i < n; i++) {
      if (st[i].zone === 'out') continue;
      for (j = i + 1; j < n; j++) {
        if (st[j].zone === 'out') continue;
        var o = overlap(V[i], V[j]);
        if (o && o.depth > EPS) { st[i].hit = true; st[j].hit = true; }
      }
    }
    for (i = 0; i < n; i++) { st[i].good = st[i].zone === 'in' && !st[i].hit; if (st[i].good) packed++; }
    return { states: st, packed: packed, solved: packed === n };
  }

  // Nudge piece i out of shallow overlaps so it rests flush against walls and
  // neighbours. Only that piece moves. Returns false (and leaves it alone) when
  // it is in the tray, buried too deep, or there is no clean resting spot nearby.
  function settle(pieces, i, C) {
    var p = pieces[i];
    if (!pointInside(C, p.x, p.y)) return false;
    var x0 = p.x, y0 = p.y, others = [], j, k, A, e, o;
    for (j = 0; j < pieces.length; j++) {
      if (j === i) continue;
      var B = verts(pieces[j]);
      if (zone(B, C) !== 'out') others.push(B);
    }
    var ok = true;
    for (var it = 0; it < 60 && ok; it++) {
      var moved = false;
      for (k = 0; k < C.walls.length && ok; k++) {
        var w = C.walls[k];
        e = excess(verts(p), w);
        if (e > 1e-10) {
          if (e > SNAP) { ok = false; break; }
          p.x -= w.nx * e; p.y -= w.ny * e; moved = true;
        }
      }
      for (k = 0; k < others.length && ok; k++) {
        o = overlap(verts(p), others[k]);
        if (o && o.depth > 1e-10) {
          if (o.depth > SNAP) { ok = false; break; }
          p.x += o.nx * o.depth; p.y += o.ny * o.depth; moved = true;
        }
      }
      if (!moved) break;
    }
    if (ok) {
      var dx = p.x - x0, dy = p.y - y0;
      if (dx * dx + dy * dy > MAX_SLIDE * MAX_SLIDE) ok = false;
    }
    if (ok) {
      A = verts(p);
      for (k = 0; k < C.walls.length; k++) if (excess(A, C.walls[k]) > EPS) ok = false;
      for (k = 0; k < others.length && ok; k++) { o = overlap(A, others[k]); if (o && o.depth > EPS) ok = false; }
    }
    if (!ok) { p.x = x0; p.y = y0; }
    return ok;
  }

  // The magnet. A piece dropped near others turns the last few degrees to line
  // up with a nearby edge, then slides into contact with whatever is closest
  // and along that contact until it meets a second neighbour, so it seats
  // itself in the nook it was dropped beside. Only this piece moves.
  var MAG_TURN = 7;      // degrees the magnet may turn a piece to match a nearby edge
  var GRID_TURN = 3;     // and to line up with the box's own walls, anywhere inside it
  var MAG_REACH = 0.2;   // how far the magnet may pull a piece towards its nearest neighbour
  var MAG_SLIDE = 0.2;   // and then along that neighbour to meet a second one

  function edgeList(V) {
    var cx = 0, cy = 0, out = [], i;
    for (i = 0; i < V.length; i++) { cx += V[i][0] / V.length; cy += V[i][1] / V.length; }
    var ns = normals(V);
    for (i = 0; i < V.length; i++) {
      var a = V[i], b = V[(i + 1) % V.length], nx = ns[i][0], ny = ns[i][1];
      if ((a[0] + b[0]) / 2 * nx + (a[1] + b[1]) / 2 * ny < cx * nx + cy * ny) { nx = -nx; ny = -ny; }
      out.push({ a: a, b: b, nx: nx, ny: ny });
    }
    return out;
  }

  // A line the piece may rest against: contact is when the piece's furthest
  // point along (ux, uy) reaches d.
  function reach(V, t) {
    var m = -Infinity;
    for (var i = 0; i < V.length; i++) { var v = V[i][0] * t.ux + V[i][1] * t.uy; if (v > m) m = v; }
    return t.d - m;
  }
  function shared(e, t) {
    var tx = -t.uy, ty = t.ux;
    var p1 = e.a[0] * tx + e.a[1] * ty, p2 = e.b[0] * tx + e.b[1] * ty;
    var q1 = t.a[0] * tx + t.a[1] * ty, q2 = t.b[0] * tx + t.b[1] * ty;
    return Math.min(Math.max(p1, p2), Math.max(q1, q2)) - Math.max(Math.min(p1, p2), Math.min(q1, q2));
  }
  function turnTo(e, t) {
    var d = (Math.atan2(t.uy, t.ux) - Math.atan2(e.ny, e.nx)) * 180 / Math.PI;
    return ((d % 360) + 540) % 360 - 180;
  }

  function span(V, nx, ny) {
    var lo = Infinity, hi = -Infinity;
    for (var i = 0; i < V.length; i++) { var d = V[i][0] * nx + V[i][1] * ny; if (d < lo) lo = d; if (d > hi) hi = d; }
    return [lo, hi];
  }
  // How far outline A can slide along unit direction (dx, dy) before it
  // touches convex B: 0 if already touching or overlapping, Infinity if never.
  function sweep(A, B, dx, dy) {
    var axes = normals(A).concat(normals(B)), enter = -Infinity, exit = Infinity;
    for (var k = 0; k < axes.length; k++) {
      var nx = axes[k][0], ny = axes[k][1], a = span(A, nx, ny), b = span(B, nx, ny), v = dx * nx + dy * ny;
      if (Math.abs(v) < 1e-9) {
        if (a[1] <= b[0] + 1e-9 || b[1] <= a[0] + 1e-9) return Infinity;
        continue;
      }
      var t1 = (b[0] - a[1]) / v, t2 = (b[1] - a[0]) / v;
      enter = Math.max(enter, Math.min(t1, t2)); exit = Math.min(exit, Math.max(t1, t2));
    }
    if (enter > exit - 1e-9 || exit <= 1e-9) return Infinity;
    return Math.max(enter, 0);
  }
  // How far A can slide before anything stops it: a neighbour or a wall.
  function travel(A, others, C, dx, dy) {
    var best = Infinity, k;
    for (k = 0; k < others.length; k++) best = Math.min(best, sweep(A, others[k], dx, dy));
    for (k = 0; k < C.walls.length; k++) {
      var w = C.walls[k], v = dx * w.nx + dy * w.ny;
      if (v > 1e-9) best = Math.min(best, Math.max(0, -excess(A, w) / v));
    }
    return best;
  }

  // Slide piece p into contact with the nearest thing, then along that
  // contact into a second one. Returns true if it moved.
  function seat(p, others, C) {
    var V = verts(p), dirs = [], k, best = null;
    for (k = 0; k < C.walls.length; k++) dirs.push([C.walls[k].nx, C.walls[k].ny]);
    others.forEach(function (B) {
      // head for B along the axis that separates the two the most
      var axes = normals(V).concat(normals(B)), pick = null;
      axes.forEach(function (n) {
        var a = span(V, n[0], n[1]), b = span(B, n[0], n[1]);
        if (b[0] - a[1] > (pick ? pick.gap : -Infinity)) pick = { gap: b[0] - a[1], x: n[0], y: n[1] };
        if (a[0] - b[1] > pick.gap) pick = { gap: a[0] - b[1], x: -n[0], y: -n[1] };
      });
      if (pick && pick.gap > 1e-9 && pick.gap <= MAG_REACH) dirs.push([pick.x, pick.y]);
    });
    dirs.forEach(function (d) {
      var t = travel(V, others, C, d[0], d[1]);
      if (t > 1e-9 && t <= MAG_REACH && (!best || t < best.t)) best = { t: t, x: d[0], y: d[1] };
    });
    if (!best) return false;
    p.x += best.x * best.t; p.y += best.y * best.t;
    V = verts(p);
    var tx = -best.y, ty = best.x, f = travel(V, others, C, tx, ty), r = travel(V, others, C, -tx, -ty);
    if (Math.min(f, r) <= MAG_SLIDE) {
      var s = f <= r ? f : -r;
      p.x += tx * s; p.y += ty * s;
    }
    return true;
  }

  // Returns true when the piece snapped somewhere clean. With keep, it stays
  // lined up even when the spot is not clean (and returns true).
  function magnet(pieces, i, C, keep) {
    var p = pieces[i];
    if (!pointInside(C, p.x, p.y)) return false;
    var x0 = p.x, y0 = p.y, a0 = p.angle, targets = [], others = [], j, k;
    for (k = 0; k < C.walls.length; k++) {
      var w = C.walls[k];
      targets.push({ ux: w.nx, uy: w.ny, d: w.d, a: C.poly[k], b: C.poly[(k + 1) % C.poly.length] });
    }
    for (j = 0; j < pieces.length; j++) {
      if (j === i) continue;
      var B = verts(pieces[j]);
      if (zone(B, C) === 'out') continue;
      others.push(B);
      edgeList(B).forEach(function (e) {
        targets.push({ ux: -e.nx, uy: -e.ny, d: -(e.nx * e.a[0] + e.ny * e.a[1]), a: e.a, b: e.b });
      });
    }

    // turn to match the nearest almost-parallel edge
    var best = null;
    edgeList(verts(p)).forEach(function (e) {
      targets.forEach(function (t) {
        var turn = turnTo(e, t);
        if (Math.abs(turn) > MAG_TURN + 1e-9) return;
        var gap = reach(verts(p), t);
        if (gap < -SNAP || gap > MAG_REACH || shared(e, t) < 0.15) return;
        var score = Math.abs(gap) + Math.abs(turn) * 0.02;
        if (!best || score < best.score) best = { turn: turn, score: score };
      });
    });
    // The box's walls are the one thing that is never crooked, so a piece a
    // few degrees off one of their directions straightens to it first; that
    // stops a slightly crooked neighbour from passing its tilt along.
    var grid = null;
    edgeList(verts(p)).forEach(function (e) {
      C.walls.forEach(function (w) {
        [1, -1].forEach(function (sgn) {
          var turn = turnTo(e, { ux: w.nx * sgn, uy: w.ny * sgn });
          if (Math.abs(turn) <= GRID_TURN + 1e-9 && (!grid || Math.abs(turn) < Math.abs(grid))) grid = turn;
        });
      });
    });
    if (grid !== null) best = { turn: grid };
    if (best) p.angle = a0 + Math.round(best.turn);

    settle(pieces, i, C);              // out of any shallow overlap first
    var moved = seat(p, others, C);
    if (!best && !moved && p.x === x0 && p.y === y0) return false;

    var V = verts(p);
    var ok = (p.x - x0) * (p.x - x0) + (p.y - y0) * (p.y - y0) <= MAX_SLIDE * MAX_SLIDE;
    for (k = 0; k < C.walls.length && ok; k++) if (excess(V, C.walls[k]) > EPS) ok = false;
    for (k = 0; k < others.length && ok; k++) { var o = overlap(V, others[k]); if (o && o.depth > EPS) ok = false; }
    if (!ok && !keep) { p.x = x0; p.y = y0; p.angle = a0; }
    return keep ? true : ok;
  }

  // Everything that happens to a piece as it is dragged to (x, y). Only that
  // piece ever moves: snap it to a nearby edge if that is a clean fit; else
  // nudge it out of shallow overlaps; else still line it up with the nearest
  // edge so a slightly crooked piece is at least straight (it stays red).
  // Returns 'snap', 'fit' or 'bad'.
  function place(pieces, i, C) {
    var p = pieces[i], x = p.x, y = p.y, a = p.angle;
    if (magnet(pieces, i, C)) return 'snap';
    if (pointInside(C, x, y) && settle(pieces, i, C)) return 'fit';
    p.x = x; p.y = y;
    if (magnet(pieces, i, C, true) && p.angle !== a) { settle(pieces, i, C); return 'bad'; }
    p.x = x; p.y = y; p.angle = a;
    settle(pieces, i, C);
    return 'bad';
  }

  // The shake. If every piece is in the box and each is close to a spot that
  // would finish the board (within SHAKE_MOVE and SHAKE_TURN degrees),
  // return those spots; otherwise null. All pieces may move here, but only
  // when the player asks for a shake.
  var SHAKE_MOVE = 0.2, SHAKE_TURN = 3;   // same reach as the magnet, and a few degrees

  function relaxAll(Q, home, C, iters) {
    var n = Q.length, V = Q.map(verts), worst = 0, i, j, k;
    function shift(i, dx, dy) {
      Q[i].x += dx; Q[i].y += dy;
      for (var m = 0; m < V[i].length; m++) { V[i][m][0] += dx; V[i][m][1] += dy; }
    }
    for (var it = 0; it < iters; it++) {
      worst = 0;
      for (i = 0; i < n; i++) {
        for (k = 0; k < C.walls.length; k++) {
          var e = excess(V[i], C.walls[k]);
          if (e > 0) { worst = Math.max(worst, e); shift(i, -C.walls[k].nx * e, -C.walls[k].ny * e); }
        }
        for (j = i + 1; j < n; j++) {
          var o = overlap(V[i], V[j]);
          if (o && o.depth > 0) {
            worst = Math.max(worst, o.depth);
            var h = o.depth / 2;
            shift(i, o.nx * h, o.ny * h); shift(j, -o.nx * h, -o.ny * h);
          }
        }
      }
      for (i = 0; i < n; i++) {   // nobody wanders further than a hair from where it was
        var dx = Q[i].x - home[i].x, dy = Q[i].y - home[i].y, d = Math.sqrt(dx * dx + dy * dy);
        if (d > SHAKE_MOVE) { var f = SHAKE_MOVE / d; shift(i, home[i].x + dx * f - Q[i].x, home[i].y + dy * f - Q[i].y); }
      }
      if (worst < EPS / 4) break;
    }
    // how much overlap is left, in total
    var left = 0;
    for (i = 0; i < n; i++) {
      for (k = 0; k < C.walls.length; k++) left += Math.max(0, excess(V[i], C.walls[k]));
      for (j = i + 1; j < n; j++) { var q = overlap(V[i], V[j]); if (q) left += q.depth; }
    }
    return { worst: worst, left: left };
  }

  function shake(pieces, C, budgetMs) {
    var n = pieces.length, i;
    for (i = 0; i < n; i++) if (!pointInside(C, pieces[i].x, pieces[i].y)) return null;
    var home = pieces.map(function (p) { return { x: p.x, y: p.y }; }), base = pieces.map(function (p) { return p.angle; });
    var until = Date.now() + (budgetMs || 150);
    function attempt(angles) {
      var Q = pieces.map(function (p, k) { return { type: p.type, size: p.size, x: p.x, y: p.y, angle: angles[k] }; });
      var r = relaxAll(Q, home, C, 150);
      return { Q: Q, r: r.left, solved: r.worst < EPS && evaluate(Q, C).solved };
    }
    var angles = base.slice(), cur = attempt(angles);
    // Good first guesses: pieces whose angles are a few degrees apart are
    // probably meant to share one, and many are meant to sit on a round angle.
    // Angles are compared modulo 30 degrees, which every shape here repeats in.
    function cluster(nudge) {
      var v = base.map(function (a, k) { return { k: k, m: ((a % 30) + 30) % 30 }; }).sort(function (p, q) { return p.m - q.m; });
      var out = base.slice(), groups = [];
      v.forEach(function (e) {
        var g = groups[groups.length - 1];
        if (g && e.m - g[g.length - 1].m <= SHAKE_TURN) g.push(e); else groups.push([e]);
      });
      if (groups.length > 1 && groups[0][0].m + 30 - groups[groups.length - 1][groups[groups.length - 1].length - 1].m <= SHAKE_TURN) {
        groups[groups.length - 1].forEach(function (e) { e.m -= 30; }); groups[0] = groups.pop().concat(groups[0]);
      }
      groups.forEach(function (g) {
        var mean = Math.round(g.reduce(function (t, e) { return t + e.m; }, 0) / g.length) + (g.length > 1 ? nudge : 0);
        g.forEach(function (e) { var d = mean - e.m; if (Math.abs(d) <= SHAKE_TURN) out[e.k] = base[e.k] + d; });
      });
      return out;
    }
    [cluster(0), cluster(-1), cluster(1), base.map(function (a) { var r = Math.round(a / 15) * 15; return Math.abs(r - a) <= SHAKE_TURN ? r : a; }),
     base.map(function (a) { var r = Math.round(a / 5) * 5; return Math.abs(r - a) <= SHAKE_TURN ? r : a; })].forEach(function (guess) {
      if (cur.solved || Date.now() > until || guess.every(function (a, k) { return a === angles[k]; })) return;
      var g = attempt(guess);
      if (g.solved || g.r < cur.r) { cur = g; angles = guess; }
    });
    // then try turning single pieces by a degree, keeping whatever helps
    for (var pass = 0; pass < 3 && !cur.solved && Date.now() < until; pass++) {
      var st = evaluate(cur.Q, C).states;
      for (i = 0; i < n && !cur.solved && Date.now() < until; i++) {
        if (st[i].good && pass === 0) continue;   // the culprits first, then anyone
        for (var d = -SHAKE_TURN; d <= SHAKE_TURN && !cur.solved; d++) {
          var trial = angles.slice(); trial[i] = base[i] + d;
          if (trial[i] === angles[i]) continue;
          var r = attempt(trial);
          if (r.solved || r.r < cur.r - 1e-6) { cur = r; angles = trial; }
        }
      }
    }
    return cur.solved ? cur.Q.map(function (q) { return { x: q.x, y: q.y, angle: q.angle }; }) : null;
  }

  function bounds(poly) {
    var b = { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity };
    for (var i = 0; i < poly.length; i++) {
      if (poly[i][0] < b.minX) b.minX = poly[i][0]; if (poly[i][0] > b.maxX) b.maxX = poly[i][0];
      if (poly[i][1] < b.minY) b.minY = poly[i][1]; if (poly[i][1] > b.maxY) b.maxY = poly[i][1];
    }
    return b;
  }

  return {
    H: H, EPS: EPS, SHAPES: SHAPES,
    verts: verts, overlap: overlap, makeContainer: makeContainer, excess: excess,
    pointInside: pointInside, zone: zone, evaluate: evaluate, settle: settle, magnet: magnet, place: place, shake: shake, bounds: bounds
  };
})();

// Packman levels. Containers are convex polygons centred on the origin, in the
// same units as the pieces (every piece has side 1). Each solution is one packed
// [x, y, angle] per piece, in the order the pieces are listed. The levels run
// from easiest to hardest; saved progress goes by name, so they can be reordered.
// Bonus levels come last, after the seventeen, and are numbered on their own.
var PackmanLevels = (function () {
  'use strict';

  var H = Math.sqrt(3) / 2;

  function box(side) {
    var h = side / 2;
    return [[-h, -h], [h, -h], [h, h], [-h, h]];
  }
  function ngon(n, radius, startDeg) {
    var out = [];
    for (var i = 0; i < n; i++) {
      var r = (startDeg + i * 360 / n) * Math.PI / 180;
      out.push([radius * Math.cos(r), radius * Math.sin(r)]);
    }
    return out;
  }
  // A whisker of breathing room on the exact-fit shapes: less than a pixel, so
  // pieces packed edge to edge still look evenly spaced.
  function loosen(poly, k) {
    return poly.map(function (p) { return [p[0] * k, p[1] * k]; });
  }
  function pieces(squares, triangles, dominoes, hexagons) {
    var out = [], i;
    for (i = 0; i < squares; i++) out.push('square');
    for (i = 0; i < triangles; i++) out.push('triangle');
    for (i = 0; i < (dominoes || 0); i++) out.push('domino');
    for (i = 0; i < (hexagons || 0); i++) out.push('hexagon');
    return out;
  }

  var roofY = (Math.sqrt(3) - 2) / 2;   // where the house's walls meet its roof

  return [
    {
      name: 'Four Square',
      intro: 'Drag every shape into the box.',
      hint: 'No tricks here. Two on top, two below.',
      container: box(2.004),
      pieces: pieces(4, 0),
      solution: [[-0.5, -0.5, 0], [0.5, -0.5, 0], [-0.5, 0.5, 0], [0.5, 0.5, 0]]
    },
    {
      name: 'Flip',
      intro: 'Shapes can spin. Pick one up, then drag its knob.',
      hint: 'Three triangles sit in the corners. The fourth goes upside-down in the middle.',
      container: loosen([[0, -4 * H / 3], [1, 2 * H / 3], [-1, 2 * H / 3]], 1.002),
      pieces: pieces(0, 4),
      solution: [[0, -0.5774, 0], [-0.5, 0.2887, 0], [0.5, 0.2887, 0], [0, 0, 180]]
    },
    {
      name: 'Honeycomb',
      intro: 'Six slices, one hexagon.',
      hint: 'Point every triangle at the centre, like a pizza. They sit 60° apart.',
      container: loosen(ngon(6, 1, 0), 1.002),
      pieces: pieces(0, 6),
      scramble: true,
      solution: [[0.5, 0.2887, 300], [0, 0.5774, 0], [-0.5, 0.2887, 60], [-0.5, -0.2887, 120], [0, -0.5774, 180], [0.5, -0.2887, 240]]
    },
    {
      name: 'Home',
      intro: 'Squares and triangles, together at last.',
      hint: 'Squares build the walls, triangles build the roof.',
      container: loosen([[-1, roofY + 2], [1, roofY + 2], [1, roofY], [0, roofY - 2 * H], [-1, roofY]], 1.004),
      pieces: pieces(4, 4),
      scramble: true,
      solution: [[-0.5, 0.366, 0], [0.5, 0.366, 0], [-0.5, 1.366, 0], [0.5, 1.366, 0], [0, -1.2887, 0], [-0.5, -0.4226, 0], [0.5, -0.4226, 0], [0, -0.7113, 180]]
    },
    {
      name: 'Lantern',
      intro: 'A honeycomb, stretched, with two squares across the middle.',
      hint: 'Two squares side by side across the middle. Three triangles above them and three below: point, flip, point.',
      container: loosen([[-1, -0.5], [-0.5, -0.5 - H], [0.5, -0.5 - H], [1, -0.5], [1, 0.5], [0.5, 0.5 + H], [-0.5, 0.5 + H], [-1, 0.5]], 1.004),
      pieces: pieces(2, 6),
      scramble: true,
      solution: [[-0.5, 0, 0], [0.5, 0, 0], [-0.5, -0.7887, 0], [0.5, -0.7887, 0], [0, -1.0774, 180], [-0.5, 0.7887, 180], [0.5, 0.7887, 180], [0, 1.0774, 0]]
    },
    {
      name: 'Tilt',
      intro: 'One triangle. One box. The box is narrower than the triangle.',
      hint: 'Lean it 15° and tuck one corner of the triangle into a corner of the box.',
      container: box(0.972),
      pieces: pieces(0, 1),
      solution: [[0.0717, 0.0717, 15]]
    },
    {
      name: 'Squeeze',
      intro: 'Three shapes. Side by side they would need a bigger box.',
      hint: 'Nothing leans. The square sits against the middle of one wall. One triangle rests flat on the floor, the other hangs flat from the ceiling, and their points meet beside the square.',
      container: box(1.783),
      pieces: pieces(1, 2),
      solution: [[0.388, 0, 0], [-0.388, 0.599, 0], [-0.388, -0.599, 180]]
    },
    {
      name: 'Five Alive',
      intro: 'Five squares in a box too small for a tidy grid.',
      hint: 'One square in each corner. The fifth sits in the middle, turned 45°.',
      fact: 'The smallest box that holds five unit squares has side 2 + 1/√2 ≈ 2.707. This one is 2.713.',
      container: box(2.713),
      pieces: pieces(5, 0),
      solution: [[-0.8565, -0.8565, 0], [0.8565, -0.8565, 0], [-0.8565, 0.8565, 0], [0.8565, 0.8565, 0], [0, 0, 45]]
    },
    {
      name: 'Dozen',
      intro: 'Twelve sides, eighteen shapes, no gaps.',
      hint: 'Six triangles make a hexagon in the middle. Put a square on each of its sides, then a triangle in every gap. Everything sits on a multiple of 30°.',
      container: loosen(ngon(12, 1 / (2 * Math.sin(Math.PI / 12)), 15), 1.004),
      pieces: pieces(6, 12),
      scramble: true,
      solution: [[1.183, 0.683, 30], [0, 1.366, 0], [-1.183, 0.683, 60], [-1.183, -0.683, 30], [0, -1.366, 0], [1.183, -0.683, 60], [0.5, 0.2887, 300], [0, 0.5774, 0], [-0.5, 0.2887, 60], [-0.5, -0.2887, 120], [0, -0.5774, 180], [0.5, -0.2887, 240], [1.5774, 0, 270], [0.7887, 1.366, 330], [-0.7887, 1.366, 30], [-1.5774, 0, 90], [-0.7887, -1.366, 150], [0.7887, -1.366, 210]]
    },
    {
      name: 'Diamond',
      intro: 'Two triangles, and a box that looks too small for them.',
      hint: 'Join them edge to edge to make a diamond. Then lay the diamond corner to corner across the box: one triangle at 15°, the other at 75°.',
      fact: 'The diamond is \u221A3 long, so it only fits along the diagonal. The smallest box is \u221A6/2 \u2248 1.225 across; this one is 1.232.',
      container: box(1.232),
      pieces: pieces(0, 2),
      solution: [[0.204, 0.204, 15], [-0.204, -0.204, 75]]
    },
    {
      name: 'Odd Couple',
      intro: 'One square, one triangle. Stacked up they would poke out of the top.',
      hint: 'The square goes snug in a corner. The triangle goes in the opposite corner, turned to 75°, so one of its edges slants across the square\u2019s free corner.',
      container: box(1.619),
      pieces: pieces(1, 1),
      solution: [[0.3095, 0.3095, 0], [-0.4013, -0.388, 75]]
    },
    {
      name: 'Tripod',
      intro: 'A triangle with barely room for two squares side by side. Fit three.',
      hint: 'Give each square its own wall. One sits flat on the floor, and the other two lie flat against the sloping sides, at 30° and 60°.',
      container: loosen([[0, -2 * H / 3], [0.5, H / 3], [-0.5, H / 3]], 3.245),
      pieces: pieces(3, 0),
      solution: [[0.6482, 0.2493, 60], [-0.1057, -0.6905, 30], [-0.5387, 0.4255, 0]]
    },
    {
      name: 'Pinwheel',
      intro: 'Three squares in a honeycomb cell. A neat row will not fit.',
      hint: 'Each square lies flat against a wall, with an empty wall between each pair. They sit at 0°, 30° and 60°, like the blades of a pinwheel.',
      container: ngon(6, 1.372, 0),
      pieces: pieces(3, 0),
      solution: [[-0.1895, 0.6822, 0], [-0.503, -0.5052, 30], [0.6795, -0.1872, 60]]
    },
    {
      name: 'Trio',
      intro: 'Three triangles, and a box that only looks big enough for two.',
      hint: 'One triangle hangs flat from the ceiling, at 60°. One stands flat against the right-hand wall, at 30°. The third tucks into the bottom-left corner at 105°.',
      container: box(1.488),
      pieces: pieces(0, 3),
      solution: [[-0.1412, -0.4553, 60], [0.4361, 0.122, 30], [-0.3358, 0.3358, 105]]
    },
    {
      name: 'Ten Tight',
      intro: 'Ten squares. A 4×4 box would be easy, so this one is smaller.',
      hint: 'Three squares in one corner, three in the opposite corner, one in each of the other two. The last two turn 45° and run down the diagonal.',
      fact: 'Best possible is 3 + 1/√2 ≈ 3.707, found by Frits Göbel in 1979 and proved in 2003. This box is 3.713.',
      container: box(3.713),
      pieces: pieces(10, 0),
      solution: [[-1.3565, -1.3565, 0], [-0.3565, -1.3565, 0], [-1.3565, -0.3565, 0], [1.3565, 1.3565, 0], [0.3565, 1.3565, 0], [1.3565, 0.3565, 0], [1.3565, -1.3565, 0], [-1.3565, 1.3565, 0], [-0.2071, 0.2012, 45], [0.5, -0.5059, 45]]
    },
    {
      name: 'Eleven',
      intro: 'One more square, and the neat patterns stop working.',
      hint: 'Six squares stay straight: one in each of two neighbouring corners, an L of three in a third corner, and one more further along that wall. The other five lean 40° in a clump.',
      fact: 'Walter Trump found this packing in 1979. The record box is 3.8771 across; this one is 3.885.',
      container: box(3.885),
      pieces: pieces(11, 0),
      solution: [[-1.4431, -1.443, 0], [1.4431, -1.4432, 0], [-1.4425, 1.4425, 0], [-0.4425, 1.4425, 0], [-1.4425, 0.4425, 0], [0.5575, 1.4436, 0], [-0.675, -0.4857, 40], [0.0212, 0.2403, 40], [1.2381, 0.4424, 40], [0.7116, -0.4858, 40], [0.0154, -1.2118, 40]]
    },
    {
      name: 'Seventeen',
      intro: 'The famously ugly one, and yes, it is hard. Pack it and a prize ships to you.',
      hint: 'Ten squares stay straight: an L of three in each bottom corner, one in each top corner, one on the top wall and one on a side wall. Six lean 40° in a 2\u00D73 block through the middle. The last one leans 37° the other way, tucked in near the top on that same side.',
      fact: 'John Bidwell found this packing in 1998. Nobody has beaten it, and nobody has proved it is the best. His box is 4.6755 across; this one is 4.68.',
      container: box(4.68),
      pieces: pieces(17, 0),
      solution: [[-1.84, 1.8406, 0], [-0.84, 1.84, 0], [-1.8405, 0.8412, 0], [1.84, 1.84, 0], [0.84, 1.84, 0], [1.84, 0.84, 0], [-1.8401, -1.8401, 0], [1.8406, -1.8405, 0], [0.0628, -1.84, 0], [1.84, -0.16, 0], [-0.9056, -1.0803, 40], [-1.6074, -0.3638, 40], [-0.0561, -0.5373, 40], [-0.6953, 0.2308, 40], [0.6356, 0.2005, 40], [-0.0026, 0.9704, 40], [0.9613, -1.0143, 323]]
    },
    {
      name: 'Brickwork',
      bonus: true,
      intro: 'A new shape: the brick, two squares long.',
      hint: 'The square goes dead centre. The four bricks chase each other round it, each one lying along a different wall.',
      container: box(3.006),
      pieces: pieces(1, 0, 4),
      solution: [[0, 0, 0], [-0.5, -1, 0], [1, -0.5, 90], [0.5, 1, 0], [-1, 0.5, 90]]
    },
    {
      name: 'Corners',
      bonus: true,
      intro: 'Another new shape: the hexagon. It takes up most of the room.',
      hint: 'The hexagon sits in the middle with three of its sides against the walls. A triangle fills each corner.',
      container: loosen([[0, -2 * H / 3], [0.5, H / 3], [-0.5, H / 3]], 3.012),
      pieces: pieces(0, 3, 0, 1),
      solution: [[0, -1.1547, 0], [-1, 0.5774, 0], [1, 0.5774, 0], [0, 0, 0]]
    },
    {
      name: 'Wedged',
      bonus: true,
      intro: 'One hexagon. It is two across, and the box is not.',
      hint: 'Turn it 15°. Two of its corners touch the side walls and two touch the floor and ceiling.',
      fact: 'The smallest square that holds a hexagon of side 1 is 2 cos 15° \u2248 1.932 across. This one is 1.94.',
      container: box(1.94),
      pieces: pieces(0, 0, 0, 1),
      solution: [[0, 0, 15]]
    },
    {
      name: 'Snug',
      bonus: true,
      intro: 'A hexagon and two triangles, in a box that fits them like a glove.',
      hint: 'Stand the hexagon on a point, at 30°, against the right-hand wall. Its sloping sides leave a notch at the top and the bottom on the left. One triangle goes in the bottom corner at 90°, pointing at the hexagon, and the other in the top corner at 75°.',
      container: box(2.321),
      pieces: pieces(0, 2, 0, 1),
      solution: [[-0.8281, 0.6605, 90], [-0.7523, -0.7523, 75], [0.2945, -0.0247, 30]]
    },
    {
      name: 'Trefoil',
      bonus: true,
      intro: 'A tiling: three hexagons and six triangles fill this hexagon with nothing left over.',
      hint: 'No hexagon goes in the middle. All three meet at the centre point, like a three-leaf clover, each one reaching out to a wall. That leaves three empty corners, and each takes a pair of triangles.',
      fact: 'A hexagon of side 2 is exactly 24 small triangles. Three hexagons use 18 of them, and the six loose triangles are the rest.',
      container: loosen(ngon(6, 2, 0), 1.004),
      pieces: pieces(0, 6, 0, 3),
      solution: [[-1.5, 0.2887, 180], [-1.5, -0.2887, 0], [0.5, 1.4434, 0], [1, 1.1547, 180], [0.5, -1.4434, 180], [1, -1.1547, 0], [1, 0, 0], [-0.5, 0.866, 0], [-0.5, -0.866, 0]]
    },
    {
      name: 'Bricked In',
      bonus: true,
      intro: 'Two bricks, and a hexagon that looks a size too small.',
      hint: 'Lay the bricks side by side to make a block, then turn the whole block to 15°. Its four corners each find a different wall.',
      container: ngon(6, 1.547, 0),
      pieces: pieces(0, 0, 2),
      solution: [[-0.02, 0.5235, 15], [0.0088, -0.5041, 15]]
    },
    {
      name: 'Twin Hex',
      bonus: true,
      intro: 'Two hexagons. Side by side they are four across; stacked they are too tall.',
      hint: 'Turn both to 15°. Put one in the top-left corner and the other in the bottom-right, so they meet along a slanted edge in the middle.',
      container: box(3.17),
      pieces: pieces(0, 0, 0, 2),
      solution: [[-0.6191, -0.6191, 15], [0.6191, 0.5923, 15]]
    },
    {
      name: 'Off Centre',
      bonus: true,
      intro: 'A hexagon inside a hexagon, with two triangles to squeeze in beside it.',
      hint: 'Keep the hexagon straight but push it into the top-left, off centre. That opens a crescent of room on the other side: one triangle goes on the right at 105°, the other at the bottom at 15°.',
      container: ngon(6, 1.487, 0),
      pieces: pieces(0, 2, 0, 1),
      solution: [[0.9293, -0.1494, 105], [0.3702, 0.8113, 15], [-0.3425, -0.2502, 0]]
    },
    {
      name: 'Rosette',
      bonus: true,
      intro: 'The big tiling: one hexagon, six squares and six triangles make a perfect twelve-sided ring.',
      hint: 'The hexagon goes dead centre. A square sits flat against each of its six sides. The six gaps between the squares are each exactly one triangle, point inwards.',
      fact: 'This is one patch of a pattern that can tile a whole floor: every corner is where a triangle, two squares and a hexagon meet.',
      container: loosen(ngon(12, 1.9318517, 15), 1.004),
      pieces: pieces(6, 6, 0, 1),
      solution: [[1.183, 0.683, 30], [0, 1.366, 0], [-1.183, 0.683, 60], [-1.183, -0.683, 30], [0, -1.366, 0], [1.183, -0.683, 60], [1.5774, 0, 30], [0.7887, 1.366, 90], [-0.7887, 1.366, 30], [-1.5774, 0, 90], [-0.7887, -1.366, 30], [0.7887, -1.366, 90], [0, 0, 0]]
    }
  ];
})();

// ---------------------------------------------------------------------------
// The leaderboard itself. Everything above this line is the game's own
// geom.js and levels.js, pasted in by tools/build-packman-worker.py so a
// score can be checked here with the very code that judges it in the game.
// ---------------------------------------------------------------------------

const G = PackmanGeom, LEVELS = PackmanLevels;
const BY_NAME = new Map(LEVELS.map((l) => [l.name, l]));
const MAIN = LEVELS.filter((l) => !l.bonus).map((l) => l.name);
const TOP = 10;            // rows returned for a board
const PER_HOUR = 60;       // scores one address may send in an hour
const BLOCKED = /fuck|shit|cunt|nigg|fag|bitch|whore|rape|nazi|hitler|porn|penis|vagina/i;

const CORS = {
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Methods": "GET, POST, OPTIONS",
	"Access-Control-Allow-Headers": "Content-Type",
	"Content-Type": "application/json",
};
const json = (body, status = 200, extra = {}) =>
	new Response(JSON.stringify(body), { status, headers: { ...CORS, ...extra } });

// The same hash the game uses to pick a player's block and animal name from
// their id, so nobody chooses their own picture.
function hash(s) {
	let h = 2166136261;
	for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); }
	return h >>> 0;
}

function cleanName(s) {
	return String(s || "").replace(/[\u0000-\u001f\u007f<>&"'`\\]/g, "").replace(/\s+/g, " ").trim().slice(0, 18);
}

// Is this really a packing of that level? The level's own pieces, put where
// the player left them, judged by the game's rules.
function packed(level, spots) {
	if (!Array.isArray(spots) || spots.length !== level.pieces.length) return false;
	const pieces = [];
	for (let i = 0; i < spots.length; i++) {
		const s = spots[i];
		if (!Array.isArray(s) || s.length !== 3 || !s.every((v) => typeof v === "number" && isFinite(v) && Math.abs(v) < 1e4)) return false;
		pieces.push({ type: level.pieces[i], size: 1, x: s[0], y: s[1], angle: s[2] });
	}
	return G.evaluate(pieces, G.makeContainer(level.container)).solved;
}

let ready = false;
async function tables(db) {
	if (ready) return;
	await db.batch([
		db.prepare("CREATE TABLE IF NOT EXISTS scores (level TEXT NOT NULL, pid TEXT NOT NULL, name TEXT NOT NULL, t REAL NOT NULL, m INTEGER NOT NULL, at INTEGER NOT NULL, PRIMARY KEY (level, pid))"),
		db.prepare("CREATE INDEX IF NOT EXISTS scores_rank ON scores (level, t, m, at)"),
		db.prepare("CREATE TABLE IF NOT EXISTS rate (k TEXT PRIMARY KEY, n INTEGER NOT NULL, exp INTEGER NOT NULL)"),
	]);
	ready = true;
}

const row = (r) => ({ name: r.name, t: r.t, m: r.m, a: hash(r.pid) });

async function board(db, level) {
	if (level === "all") {
		// only players who have packed every one of the seventeen, by their combined best times
		const marks = MAIN.map(() => "?").join(",");
		const top = await db.prepare(
			`SELECT pid, MAX(name) AS name, SUM(t) AS t, SUM(m) AS m FROM scores WHERE level IN (${marks})
			 GROUP BY pid HAVING COUNT(*) = ${MAIN.length} ORDER BY t, m LIMIT ${TOP}`
		).bind(...MAIN).all();
		const n = await db.prepare(
			`SELECT COUNT(*) AS n FROM (SELECT pid FROM scores WHERE level IN (${marks}) GROUP BY pid HAVING COUNT(*) = ${MAIN.length})`
		).bind(...MAIN).first();
		return { level, top: top.results.map(row), of: n ? n.n : 0 };
	}
	const top = await db.prepare(`SELECT pid, name, t, m FROM scores WHERE level = ? ORDER BY t, m, at LIMIT ${TOP}`).bind(level).all();
	const n = await db.prepare("SELECT COUNT(*) AS n FROM scores WHERE level = ?").bind(level).first();
	return { level, top: top.results.map(row), of: n ? n.n : 0 };
}

async function tooMany(db, request) {
	const ip = request.headers.get("CF-Connecting-IP") || "?";
	const hour = Math.floor(Date.now() / 3600000);
	// the address is never stored, only a hash of it with the hour
	const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(ip + "|" + hour));
	const k = Array.from(new Uint8Array(bytes).slice(0, 12), (b) => b.toString(16).padStart(2, "0")).join("");
	const r = await db.prepare(
		"INSERT INTO rate (k, n, exp) VALUES (?, 1, ?) ON CONFLICT (k) DO UPDATE SET n = n + 1 RETURNING n"
	).bind(k, (hour + 2) * 3600).first();
	if (r && r.n === 1 && Math.random() < 0.05) await db.prepare("DELETE FROM rate WHERE exp < ?").bind(Math.floor(Date.now() / 1000)).run();
	return r && r.n > PER_HOUR;
}

async function submit(db, request) {
	let b;
	try { b = await request.json(); } catch (e) { return json({ error: "body" }, 400); }
	const level = BY_NAME.get(b && b.level);
	if (!level) return json({ error: "level" }, 400);
	const pid = String(b.pid || "");
	if (!/^[A-Za-z0-9-]{16,48}$/.test(pid)) return json({ error: "pid" }, 400);
	const name = cleanName(b.name);
	if (!name || BLOCKED.test(name.replace(/[^a-z]/gi, ""))) return json({ error: "name" }, 400);
	const t = Math.round(Number(b.t) * 10) / 10, m = Math.round(Number(b.m));
	// every piece has to be moved at least once, and nobody does that in under half a second each
	const n = level.pieces.length;
	if (!isFinite(t) || !isFinite(m) || m < n || m > 100000 || t < n * 0.5 || t > 86400) return json({ error: "score" }, 400);
	if (!packed(level, b.p)) return json({ error: "unpacked" }, 400);
	if (await tooMany(db, request)) return json({ error: "slow down" }, 429);

	const now = Math.floor(Date.now() / 1000);
	await db.batch([
		// a player has one row a level, and it only ever gets faster
		db.prepare(
			"INSERT INTO scores (level, pid, name, t, m, at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (level, pid) DO UPDATE SET t = excluded.t, m = excluded.m, at = excluded.at WHERE excluded.t < scores.t"
		).bind(level.name, pid, name, t, m, now),
		db.prepare("UPDATE scores SET name = ? WHERE pid = ?").bind(name, pid),
	]);
	const mine = await db.prepare("SELECT t, m FROM scores WHERE level = ? AND pid = ?").bind(level.name, pid).first();
	const ahead = await db.prepare(
		"SELECT COUNT(*) AS n FROM scores WHERE level = ? AND (t < ? OR (t = ? AND m < ?))"
	).bind(level.name, mine.t, mine.t, mine.m).first();
	return json({ ...(await board(db, level.name)), best: mine, rank: ahead.n + 1 });
}

export default {
	async fetch(request, env) {
		if (request.method === "OPTIONS") return new Response(null, { headers: CORS });
		const db = env.DB || env.db;   // the binding's name, in either case
		if (!db) return json({ error: "no database bound as DB" }, 500);
		try {
			await tables(db);
			if (request.method === "POST") return await submit(db, request);
			if (request.method !== "GET") return json({ error: "method" }, 405);
			const level = new URL(request.url).searchParams.get("level") || "all";
			if (level !== "all" && !BY_NAME.has(level)) return json({ error: "level" }, 400);
			return json(await board(db, level), 200, { "Cache-Control": "public, max-age=20" });
		} catch (err) {
			return json({ error: "exception", detail: String(err) }, 500);
		}
	},
};
