// Cloudflare Worker — the Packman leaderboard.
//
// GENERATED by packman/tools/build-worker.py from packman/geom.js,
// packman/levels.js and packman-scores.src.js. Edit those, not this file.
//
// GET  /api/packman              the top ten: most levels packed, then fewest moves, then least time
// GET  /api/packman?pid=<id>     the same, with where that player stands
// GET  /api/packman?top=100      up to a hundred rows in place of ten
// DELETE /api/packman?pid=<id>   takes that player off the board
// POST /api/packman              {level, pid, name, t, m, p} one win; p is where every piece ended up
//
// Deploy via the Cloudflare dashboard:
//   1. Storage & databases -> D1 -> Create database (name: packman).
//   2. Workers & Pages -> Create -> Worker (name: packman-scores) -> Edit code -> paste this file -> Deploy.
//   3. That worker -> Settings -> Bindings -> Add -> D1 database: variable name DB, database packman.
//   4. That worker -> Settings -> Domains & Routes -> Add route: www.garvitgupta.com/api/packman*
// The tables make themselves on the first request.
//
// Housekeeping, from the D1 console:
//   SELECT * FROM scores ORDER BY at DESC LIMIT 50;      -- the latest scores
//   DELETE FROM scores WHERE name = 'someone';           -- take a player off the board

// Packman geometry: convex-polygon overlap, containment, and the drop "settle".
// World units: a size-1 square has side 1. Angles are whole degrees, y points down.
var PackmanGeom = (function () {
  'use strict';

  var H = Math.sqrt(3) / 2;
  var SHAPES = {
    square: [[-0.5, -0.5], [0.5, -0.5], [0.5, 0.5], [-0.5, 0.5]],
    triangle: [[0, -2 * H / 3], [0.5, H / 3], [-0.5, H / 3]],   // centroid at the origin
    domino: [[-1, -0.5], [1, -0.5], [1, 0.5], [-1, 0.5]],
    hexagon: [[1, 0], [0.5, H], [-0.5, H], [-1, 0], [-0.5, -H], [0.5, -H]]
  };

  // How much pieces may sink into each other or a wall and still count as packed.
  // Kept tiny on purpose: the last level's container is only ~0.03 tighter than
  // the easy 45-degree packing, so a generous tolerance would let that one through.
  var EPS = 0.002;
  var SNAP = 0.22;      // deepest overlap the settle will push out of
  var MAX_SLIDE = 0.5;  // furthest a settle may move a piece from where it was dropped

  function verts(p) {
    var base = SHAPES[p.type], s = p.size || 1;
    var r = p.angle * Math.PI / 180, c = Math.cos(r), n = Math.sin(r);
    var out = [];
    for (var i = 0; i < base.length; i++) {
      var x = base[i][0] * s, y = base[i][1] * s;
      out.push([p.x + x * c - y * n, p.y + x * n + y * c]);
    }
    return out;
  }

  function normals(poly) {
    var out = [];
    for (var i = 0; i < poly.length; i++) {
      var a = poly[i], b = poly[(i + 1) % poly.length];
      var dx = b[0] - a[0], dy = b[1] - a[1], l = Math.sqrt(dx * dx + dy * dy);
      out.push([dy / l, -dx / l]);
    }
    return out;
  }

  // Separating-axis test. null if apart; otherwise the shallowest way out,
  // as a unit direction to move A plus the distance.
  function overlap(A, B) {
    var best = null, axes = normals(A).concat(normals(B));
    for (var k = 0; k < axes.length; k++) {
      var nx = axes[k][0], ny = axes[k][1];
      var minA = Infinity, maxA = -Infinity, minB = Infinity, maxB = -Infinity, i, d;
      for (i = 0; i < A.length; i++) { d = A[i][0] * nx + A[i][1] * ny; if (d < minA) minA = d; if (d > maxA) maxA = d; }
      for (i = 0; i < B.length; i++) { d = B[i][0] * nx + B[i][1] * ny; if (d < minB) minB = d; if (d > maxB) maxB = d; }
      var fwd = maxB - minA, back = maxA - minB;
      if (fwd <= 0 || back <= 0) return null;
      if (!best || fwd < best.depth) best = { depth: fwd, nx: nx, ny: ny };
      if (back < best.depth) best = { depth: back, nx: -nx, ny: -ny };
    }
    return best;
  }

  // A convex container as half-planes with outward normals: inside is n.p <= d.
  function makeContainer(poly) {
    var cx = 0, cy = 0, i;
    for (i = 0; i < poly.length; i++) { cx += poly[i][0] / poly.length; cy += poly[i][1] / poly.length; }
    var ns = normals(poly), walls = [];
    for (i = 0; i < poly.length; i++) {
      var nx = ns[i][0], ny = ns[i][1], d = poly[i][0] * nx + poly[i][1] * ny;
      if (cx * nx + cy * ny > d) { nx = -nx; ny = -ny; d = -d; }
      walls.push({ nx: nx, ny: ny, d: d });
    }
    return { poly: poly, walls: walls };
  }

  // A level may have more than one box on its board. Then the container is a list of convex ones
  // (parts), and each shape is judged by the box it is in, or the nearest: see part.
  function makeBoxes(polys) {
    var parts = polys.map(makeContainer), poly = [], walls = [];
    parts.forEach(function (c) { poly = poly.concat(c.poly); walls = walls.concat(c.walls); });
    return { poly: poly, walls: walls, parts: parts };
  }
  // The box a point belongs to: the one it is inside, or failing that the one it is least far out of.
  function part(C, x, y) {
    if (!C.parts) return C;
    var best = null, least = Infinity;
    C.parts.forEach(function (c) {
      var m = -Infinity;
      c.walls.forEach(function (w) { m = Math.max(m, x * w.nx + y * w.ny - w.d); });
      if (m < least) { least = m; best = c; }
    });
    return best;
  }

  // How far a polygon pokes through one wall (negative when clear of it).
  function excess(A, w) {
    var m = -Infinity;
    for (var i = 0; i < A.length; i++) { var d = A[i][0] * w.nx + A[i][1] * w.ny; if (d > m) m = d; }
    return m - w.d;
  }

  function pointInside(C, x, y) {
    if (C.parts) return C.parts.some(function (c) { return pointInside(c, x, y); });
    for (var i = 0; i < C.walls.length; i++) {
      var w = C.walls[i];
      if (x * w.nx + y * w.ny > w.d) return false;
    }
    return true;
  }

  // 'in' fully inside, 'out' clear of the container, 'edge' straddling a wall.
  function zone(A, C) {
    if (C.parts) {
      var all = C.parts.map(function (c) { return zone(A, c); });
      return all.indexOf('in') >= 0 ? 'in' : all.indexOf('edge') >= 0 ? 'edge' : 'out';
    }
    var worst = -Infinity;
    for (var i = 0; i < C.walls.length; i++) { var e = excess(A, C.walls[i]); if (e > worst) worst = e; }
    if (worst <= EPS) return 'in';
    var o = overlap(A, C.poly);
    return (!o || o.depth <= EPS) ? 'out' : 'edge';
  }

  // Judge the whole board. Pieces left out in the tray never count as colliding.
  function evaluate(pieces, C) {
    var n = pieces.length, V = [], st = [], i, j, packed = 0;
    for (i = 0; i < n; i++) { V.push(verts(pieces[i])); st.push({ zone: zone(V[i], C), hit: false }); }
    for (i = 0; i < n; i++) {
      if (st[i].zone === 'out') continue;
      for (j = i + 1; j < n; j++) {
        if (st[j].zone === 'out') continue;
        var o = overlap(V[i], V[j]);
        if (o && o.depth > EPS) { st[i].hit = true; st[j].hit = true; }
      }
    }
    for (i = 0; i < n; i++) { st[i].good = st[i].zone === 'in' && !st[i].hit; if (st[i].good) packed++; }
    return { states: st, packed: packed, solved: packed === n };
  }

  // Nudge piece i out of shallow overlaps so it rests flush against walls and
  // neighbours. Only that piece moves. Returns false (and leaves it alone) when
  // it is in the tray, buried too deep, or there is no clean resting spot nearby.
  function settle(pieces, i, C) {
    var p = pieces[i];
    if (!pointInside(C, p.x, p.y)) return false;
    C = part(C, p.x, p.y);
    var x0 = p.x, y0 = p.y, others = [], j, k, A, e, o;
    for (j = 0; j < pieces.length; j++) {
      if (j === i) continue;
      var B = verts(pieces[j]);
      if (zone(B, C) !== 'out') others.push(B);
    }
    var ok = true;
    for (var it = 0; it < 60 && ok; it++) {
      var moved = false;
      for (k = 0; k < C.walls.length && ok; k++) {
        var w = C.walls[k];
        e = excess(verts(p), w);
        if (e > 1e-10) {
          if (e > SNAP) { ok = false; break; }
          p.x -= w.nx * e; p.y -= w.ny * e; moved = true;
        }
      }
      for (k = 0; k < others.length && ok; k++) {
        o = overlap(verts(p), others[k]);
        if (o && o.depth > 1e-10) {
          if (o.depth > SNAP) { ok = false; break; }
          p.x += o.nx * o.depth; p.y += o.ny * o.depth; moved = true;
        }
      }
      if (!moved) break;
    }
    if (ok) {
      var dx = p.x - x0, dy = p.y - y0;
      if (dx * dx + dy * dy > MAX_SLIDE * MAX_SLIDE) ok = false;
    }
    if (ok) {
      A = verts(p);
      for (k = 0; k < C.walls.length; k++) if (excess(A, C.walls[k]) > EPS) ok = false;
      for (k = 0; k < others.length && ok; k++) { o = overlap(A, others[k]); if (o && o.depth > EPS) ok = false; }
    }
    if (!ok) { p.x = x0; p.y = y0; }
    return ok;
  }

  // The magnet. A piece dropped near others turns the last few degrees to line
  // up with a nearby edge, then slides into contact with whatever is closest
  // and along that contact until it meets a second neighbour, so it seats
  // itself in the nook it was dropped beside. Only this piece moves.
  var MAG_TURN = 7;      // degrees the magnet may turn a piece to match a nearby edge
  var GRID_TURN = 3;     // and to line up with the box's own walls, anywhere inside it
  var MAG_REACH = 0.1;   // how far the magnet may pull a piece towards its nearest neighbour
  // ...and then along that neighbour to meet a second one. This is kept short: a piece is
  // dragged through here continuously, and in a slot with only a little play a long slide
  // would haul it to the nearer end however the player moved, even against the way they
  // were dragging.
  var MAG_SLIDE = 0.08;

  function edgeList(V) {
    var cx = 0, cy = 0, out = [], i;
    for (i = 0; i < V.length; i++) { cx += V[i][0] / V.length; cy += V[i][1] / V.length; }
    var ns = normals(V);
    for (i = 0; i < V.length; i++) {
      var a = V[i], b = V[(i + 1) % V.length], nx = ns[i][0], ny = ns[i][1];
      if ((a[0] + b[0]) / 2 * nx + (a[1] + b[1]) / 2 * ny < cx * nx + cy * ny) { nx = -nx; ny = -ny; }
      out.push({ a: a, b: b, nx: nx, ny: ny });
    }
    return out;
  }

  // A line the piece may rest against: contact is when the piece's furthest
  // point along (ux, uy) reaches d.
  function reach(V, t) {
    var m = -Infinity;
    for (var i = 0; i < V.length; i++) { var v = V[i][0] * t.ux + V[i][1] * t.uy; if (v > m) m = v; }
    return t.d - m;
  }
  function shared(e, t) {
    var tx = -t.uy, ty = t.ux;
    var p1 = e.a[0] * tx + e.a[1] * ty, p2 = e.b[0] * tx + e.b[1] * ty;
    var q1 = t.a[0] * tx + t.a[1] * ty, q2 = t.b[0] * tx + t.b[1] * ty;
    return Math.min(Math.max(p1, p2), Math.max(q1, q2)) - Math.max(Math.min(p1, p2), Math.min(q1, q2));
  }
  function turnTo(e, t) {
    var d = (Math.atan2(t.uy, t.ux) - Math.atan2(e.ny, e.nx)) * 180 / Math.PI;
    return ((d % 360) + 540) % 360 - 180;
  }

  function span(V, nx, ny) {
    var lo = Infinity, hi = -Infinity;
    for (var i = 0; i < V.length; i++) { var d = V[i][0] * nx + V[i][1] * ny; if (d < lo) lo = d; if (d > hi) hi = d; }
    return [lo, hi];
  }
  // How far outline A can slide along unit direction (dx, dy) before it
  // touches convex B: 0 if already touching or overlapping, Infinity if never.
  function sweep(A, B, dx, dy) {
    var axes = normals(A).concat(normals(B)), enter = -Infinity, exit = Infinity;
    for (var k = 0; k < axes.length; k++) {
      var nx = axes[k][0], ny = axes[k][1], a = span(A, nx, ny), b = span(B, nx, ny), v = dx * nx + dy * ny;
      if (Math.abs(v) < 1e-9) {
        if (a[1] <= b[0] + 1e-9 || b[1] <= a[0] + 1e-9) return Infinity;
        continue;
      }
      var t1 = (b[0] - a[1]) / v, t2 = (b[1] - a[0]) / v;
      enter = Math.max(enter, Math.min(t1, t2)); exit = Math.min(exit, Math.max(t1, t2));
    }
    if (enter > exit - 1e-9 || exit <= 1e-9) return Infinity;
    return Math.max(enter, 0);
  }
  // How far A can slide before anything stops it: a neighbour or a wall.
  function travel(A, others, C, dx, dy) {
    var best = Infinity, k;
    for (k = 0; k < others.length; k++) best = Math.min(best, sweep(A, others[k], dx, dy));
    for (k = 0; k < C.walls.length; k++) {
      var w = C.walls[k], v = dx * w.nx + dy * w.ny;
      if (v > 1e-9) best = Math.min(best, Math.max(0, -excess(A, w) / v));
    }
    return best;
  }

  // Slide piece p into contact with the nearest thing, then along that
  // contact into a second one. Returns true if it moved.
  function seat(p, others, C) {
    // Each way it might go is towards one particular thing, and carries how far off that
    // thing is. A way only counts if the piece can get there: if something else stops it
    // first, going that way would not seat it against what it was heading for, only shove
    // it sideways into the thing in between.
    var V = verts(p), dirs = [], k, best = null;
    for (k = 0; k < C.walls.length; k++) dirs.push([C.walls[k].nx, C.walls[k].ny, Math.max(0, -excess(V, C.walls[k]))]);
    others.forEach(function (B) {
      // head for B along the axis that separates the two the most
      var axes = normals(V).concat(normals(B)), pick = null;
      axes.forEach(function (n) {
        var a = span(V, n[0], n[1]), b = span(B, n[0], n[1]);
        if (b[0] - a[1] > (pick ? pick.gap : -Infinity)) pick = { gap: b[0] - a[1], x: n[0], y: n[1] };
        if (a[0] - b[1] > pick.gap) pick = { gap: a[0] - b[1], x: -n[0], y: -n[1] };
      });
      if (pick && pick.gap > 1e-9 && pick.gap <= MAG_REACH) dirs.push([pick.x, pick.y, sweep(V, B, pick.x, pick.y)]);
    });
    dirs.forEach(function (d) {
      var t = travel(V, others, C, d[0], d[1]);
      if (t < d[2] - 1e-9) return;   // stopped short of what it was heading for
      if (t > 1e-9 && t <= MAG_REACH && (!best || t < best.t)) best = { t: t, x: d[0], y: d[1] };
    });
    if (!best) return false;
    p.x += best.x * best.t; p.y += best.y * best.t;
    V = verts(p);
    var tx = -best.y, ty = best.x, f = travel(V, others, C, tx, ty), r = travel(V, others, C, -tx, -ty);
    if (Math.min(f, r) <= MAG_SLIDE) {
      var s = f <= r ? f : -r;
      p.x += tx * s; p.y += ty * s;
    }
    return true;
  }

  // Is the outline resting against a wall or another piece?
  function touching(V, others, C) {
    var k, near = 1e-4;
    for (k = 0; k < C.walls.length; k++) if (-excess(V, C.walls[k]) <= near) return true;
    return others.some(function (B) {
      var apart = -Infinity;
      normals(V).concat(normals(B)).forEach(function (n) {
        var a = span(V, n[0], n[1]), b = span(B, n[0], n[1]);
        apart = Math.max(apart, b[0] - a[1], a[0] - b[1]);
      });
      return apart <= near;
    });
  }

  // Returns true when the piece snapped somewhere clean. With keep, it stays
  // lined up even when the spot is not clean (and returns true).
  function magnet(pieces, i, C, keep) {
    var p = pieces[i];
    if (!pointInside(C, p.x, p.y)) return false;
    var whole = C;
    C = part(C, p.x, p.y);
    var x0 = p.x, y0 = p.y, a0 = p.angle, targets = [], others = [], j, k;
    for (k = 0; k < C.walls.length; k++) {
      var w = C.walls[k];
      targets.push({ ux: w.nx, uy: w.ny, d: w.d, a: C.poly[k], b: C.poly[(k + 1) % C.poly.length] });
    }
    for (j = 0; j < pieces.length; j++) {
      if (j === i) continue;
      var B = verts(pieces[j]);
      if (zone(B, C) === 'out') continue;
      others.push(B);
      edgeList(B).forEach(function (e) {
        targets.push({ ux: -e.nx, uy: -e.ny, d: -(e.nx * e.a[0] + e.ny * e.a[1]), a: e.a, b: e.b });
      });
    }

    // turn to match the nearest almost-parallel edge
    var best = null;
    edgeList(verts(p)).forEach(function (e) {
      targets.forEach(function (t) {
        var turn = turnTo(e, t);
        if (Math.abs(turn) > MAG_TURN + 1e-9) return;
        var gap = reach(verts(p), t);
        if (gap < -SNAP || gap > MAG_REACH || shared(e, t) < 0.15) return;
        var score = Math.abs(gap) + Math.abs(turn) * 0.02;
        if (!best || score < best.score) best = { turn: turn, score: score };
      });
    });
    // The box's walls are the one thing that is never crooked, so a piece a
    // few degrees off one of their directions straightens to it first; that
    // stops a slightly crooked neighbour from passing its tilt along.
    var grid = null;
    edgeList(verts(p)).forEach(function (e) {
      C.walls.forEach(function (w) {
        [1, -1].forEach(function (sgn) {
          var turn = turnTo(e, { ux: w.nx * sgn, uy: w.ny * sgn });
          if (Math.abs(turn) <= GRID_TURN + 1e-9 && (!grid || Math.abs(turn) < Math.abs(grid))) grid = turn;
        });
      });
    });
    if (grid !== null) best = { turn: grid };
    if (best) p.angle = a0 + Math.round(best.turn);

    settle(pieces, i, whole);          // out of any shallow overlap first
    var moved = seat(p, others, C);
    if (!best && !moved && p.x === x0 && p.y === y0) return false;
    // The turn and the pull are one snap. A piece that would be straightened but is still
    // too far off to be pulled into contact, and is touching nothing, is left as it was:
    // otherwise it is seen to turn first and jump into place only once it is brought closer.
    if (p.angle !== a0 && !keep && !moved && p.x === x0 && p.y === y0 && !touching(verts(p), others, C)) { p.angle = a0; return false; }

    var V = verts(p);
    var ok = (p.x - x0) * (p.x - x0) + (p.y - y0) * (p.y - y0) <= MAX_SLIDE * MAX_SLIDE;
    for (k = 0; k < C.walls.length && ok; k++) if (excess(V, C.walls[k]) > EPS) ok = false;
    for (k = 0; k < others.length && ok; k++) { var o = overlap(V, others[k]); if (o && o.depth > EPS) ok = false; }
    if (!ok && !keep) { p.x = x0; p.y = y0; p.angle = a0; }
    return keep ? true : ok;
  }

  // Everything that happens to a piece as it is dragged to (x, y). Only that
  // piece ever moves: snap it to a nearby edge if that is a clean fit; else
  // nudge it out of shallow overlaps; else still line it up with the nearest
  // edge so a slightly crooked piece is at least straight (it stays red).
  // Returns 'snap', 'fit' or 'bad'.
  function place(pieces, i, C) {
    var p = pieces[i], x = p.x, y = p.y, a = p.angle;
    if (magnet(pieces, i, C)) return 'snap';
    if (pointInside(C, x, y) && settle(pieces, i, C)) return 'fit';
    p.x = x; p.y = y;
    if (magnet(pieces, i, C, true) && p.angle !== a) { settle(pieces, i, C); return 'bad'; }
    p.x = x; p.y = y; p.angle = a;
    settle(pieces, i, C);
    return 'bad';
  }

  // The shake. If every piece is in the box and each is close to a spot that
  // would finish the board (within SHAKE_MOVE and SHAKE_TURN degrees),
  // return those spots; otherwise null. All pieces may move here, but only
  // when the player asks for a shake.
  var SHAKE_MOVE = 0.2, SHAKE_TURN = 3;   // same reach as the magnet, and a few degrees

  function relaxAll(Q, home, C, iters) {
    var n = Q.length, V = Q.map(verts), worst = 0, i, j, k;
    var W = home.map(function (h) { return part(C, h.x, h.y).walls; });   // each shape's own box
    function shift(i, dx, dy) {
      Q[i].x += dx; Q[i].y += dy;
      for (var m = 0; m < V[i].length; m++) { V[i][m][0] += dx; V[i][m][1] += dy; }
    }
    for (var it = 0; it < iters; it++) {
      worst = 0;
      for (i = 0; i < n; i++) {
        for (k = 0; k < W[i].length; k++) {
          var e = excess(V[i], W[i][k]);
          if (e > 0) { worst = Math.max(worst, e); shift(i, -W[i][k].nx * e, -W[i][k].ny * e); }
        }
        for (j = i + 1; j < n; j++) {
          var o = overlap(V[i], V[j]);
          if (o && o.depth > 0) {
            worst = Math.max(worst, o.depth);
            var h = o.depth / 2;
            shift(i, o.nx * h, o.ny * h); shift(j, -o.nx * h, -o.ny * h);
          }
        }
      }
      for (i = 0; i < n; i++) {   // nobody wanders further than a hair from where it was
        var dx = Q[i].x - home[i].x, dy = Q[i].y - home[i].y, d = Math.sqrt(dx * dx + dy * dy);
        if (d > SHAKE_MOVE) { var f = SHAKE_MOVE / d; shift(i, home[i].x + dx * f - Q[i].x, home[i].y + dy * f - Q[i].y); }
      }
      if (worst < EPS / 4) break;
    }
    // how much overlap is left, in total
    var left = 0;
    for (i = 0; i < n; i++) {
      for (k = 0; k < W[i].length; k++) left += Math.max(0, excess(V[i], W[i][k]));
      for (j = i + 1; j < n; j++) { var q = overlap(V[i], V[j]); if (q) left += q.depth; }
    }
    return { worst: worst, left: left };
  }

  function shake(pieces, C, budgetMs) {
    var n = pieces.length, i;
    for (i = 0; i < n; i++) if (!pointInside(C, pieces[i].x, pieces[i].y)) return null;
    var home = pieces.map(function (p) { return { x: p.x, y: p.y }; }), base = pieces.map(function (p) { return p.angle; });
    var until = Date.now() + (budgetMs || 150);
    function attempt(angles) {
      var Q = pieces.map(function (p, k) { return { type: p.type, size: p.size, x: p.x, y: p.y, angle: angles[k] }; });
      var r = relaxAll(Q, home, C, 150);
      return { Q: Q, r: r.left, solved: r.worst < EPS && evaluate(Q, C).solved };
    }
    var angles = base.slice(), cur = attempt(angles);
    // Good first guesses: pieces whose angles are a few degrees apart are
    // probably meant to share one, and many are meant to sit on a round angle.
    // Angles are compared modulo 30 degrees, which every shape here repeats in.
    function cluster(nudge) {
      var v = base.map(function (a, k) { return { k: k, m: ((a % 30) + 30) % 30 }; }).sort(function (p, q) { return p.m - q.m; });
      var out = base.slice(), groups = [];
      v.forEach(function (e) {
        var g = groups[groups.length - 1];
        if (g && e.m - g[g.length - 1].m <= SHAKE_TURN) g.push(e); else groups.push([e]);
      });
      if (groups.length > 1 && groups[0][0].m + 30 - groups[groups.length - 1][groups[groups.length - 1].length - 1].m <= SHAKE_TURN) {
        groups[groups.length - 1].forEach(function (e) { e.m -= 30; }); groups[0] = groups.pop().concat(groups[0]);
      }
      groups.forEach(function (g) {
        var mean = Math.round(g.reduce(function (t, e) { return t + e.m; }, 0) / g.length) + (g.length > 1 ? nudge : 0);
        g.forEach(function (e) { var d = mean - e.m; if (Math.abs(d) <= SHAKE_TURN) out[e.k] = base[e.k] + d; });
      });
      return out;
    }
    [cluster(0), cluster(-1), cluster(1), base.map(function (a) { var r = Math.round(a / 15) * 15; return Math.abs(r - a) <= SHAKE_TURN ? r : a; }),
     base.map(function (a) { var r = Math.round(a / 5) * 5; return Math.abs(r - a) <= SHAKE_TURN ? r : a; })].forEach(function (guess) {
      if (cur.solved || Date.now() > until || guess.every(function (a, k) { return a === angles[k]; })) return;
      var g = attempt(guess);
      if (g.solved || g.r < cur.r) { cur = g; angles = guess; }
    });
    // then try turning single pieces by a degree, keeping whatever helps
    for (var pass = 0; pass < 3 && !cur.solved && Date.now() < until; pass++) {
      var st = evaluate(cur.Q, C).states;
      for (i = 0; i < n && !cur.solved && Date.now() < until; i++) {
        if (st[i].good && pass === 0) continue;   // the culprits first, then anyone
        for (var d = -SHAKE_TURN; d <= SHAKE_TURN && !cur.solved; d++) {
          var trial = angles.slice(); trial[i] = base[i] + d;
          if (trial[i] === angles[i]) continue;
          var r = attempt(trial);
          if (r.solved || r.r < cur.r - 1e-6) { cur = r; angles = trial; }
        }
      }
    }
    return cur.solved ? cur.Q.map(function (q) { return { x: q.x, y: q.y, angle: q.angle }; }) : null;
  }

  function bounds(poly) {
    var b = { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity };
    for (var i = 0; i < poly.length; i++) {
      if (poly[i][0] < b.minX) b.minX = poly[i][0]; if (poly[i][0] > b.maxX) b.maxX = poly[i][0];
      if (poly[i][1] < b.minY) b.minY = poly[i][1]; if (poly[i][1] > b.maxY) b.maxY = poly[i][1];
    }
    return b;
  }

  return {
    H: H, EPS: EPS, SHAPES: SHAPES,
    verts: verts, overlap: overlap, makeContainer: makeContainer, makeBoxes: makeBoxes, part: part, excess: excess,
    pointInside: pointInside, zone: zone, evaluate: evaluate, settle: settle, magnet: magnet, place: place, shake: shake, bounds: bounds, sweep: sweep
  };
})();

// Packman levels. Containers are convex polygons centred on the origin, in the
// same units as the pieces (every piece has side 1). Each solution is one packed
// [x, y, angle] per piece, in the order the pieces are listed. The levels run
// from easiest to hardest; saved progress goes by name, so they can be reordered.
// There are four chapters, played in this order: the seventeen; then the powers; then the bricks and
// hexagons; then the twists, which are listed last here. In this file: the first is the seventeen; the next (bonus: true) brings
// the brick and the hexagon; the third (powers: n) deals n of its shapes a power each time,
// picked at random, but for any named in sure, which always come. A chameleon is dealt to
// any shape, unless chameleon: n names one; masked is the hint to give when there is a chameleon in the deal.
// Its first five levels are tidy tilings, to meet the powers on; from the sixth on they are tight packings. Each chapter is numbered on its own.
var PackmanLevels = (function () {
  'use strict';

  var H = Math.sqrt(3) / 2;

  function box(side) {
    var h = side / 2;
    return [[-h, -h], [h, -h], [h, h], [-h, h]];
  }
  function rect(w, h) {
    return [[-w / 2, -h / 2], [w / 2, -h / 2], [w / 2, h / 2], [-w / 2, h / 2]];
  }
  function ngon(n, radius, startDeg) {
    var out = [];
    for (var i = 0; i < n; i++) {
      var r = (startDeg + i * 360 / n) * Math.PI / 180;
      out.push([radius * Math.cos(r), radius * Math.sin(r)]);
    }
    return out;
  }
  // A whisker of breathing room on the exact-fit shapes: less than a pixel, so
  // pieces packed edge to edge still look evenly spaced.
  function loosen(poly, k) {
    return poly.map(function (p) { return [p[0] * k, p[1] * k]; });
  }
  function pieces(squares, triangles, dominoes, hexagons) {
    var out = [], i;
    for (i = 0; i < squares; i++) out.push('square');
    for (i = 0; i < triangles; i++) out.push('triangle');
    for (i = 0; i < (dominoes || 0); i++) out.push('domino');
    for (i = 0; i < (hexagons || 0); i++) out.push('hexagon');
    return out;
  }

  var roofY = (Math.sqrt(3) - 2) / 2;   // where the house's walls meet its roof

  return [
    {
      name: 'Four Square',
      intro: 'Drag every shape into the box.',
      hint: 'No tricks here. Two on top, two below.',
      container: box(2.004),
      pieces: pieces(4, 0),
      solution: [[-0.5, -0.5, 0], [0.5, -0.5, 0], [-0.5, 0.5, 0], [0.5, 0.5, 0]]
    },
    {
      name: 'Flip',
      intro: 'Shapes can spin. Pick one up, then drag its knob.',
      hint: 'Three triangles sit in the corners. The fourth goes upside-down in the middle.',
      container: loosen([[0, -4 * H / 3], [1, 2 * H / 3], [-1, 2 * H / 3]], 1.002),
      pieces: pieces(0, 4),
      solution: [[0, -0.5774, 0], [-0.5, 0.2887, 0], [0.5, 0.2887, 0], [0, 0, 180]]
    },
    {
      name: 'Honeycomb',
      intro: 'Six slices, one hexagon.',
      hint: 'Point every triangle at the centre, like a pizza. They sit 60° apart.',
      container: loosen(ngon(6, 1, 0), 1.002),
      pieces: pieces(0, 6),
      scramble: true,
      solution: [[0.5, 0.2887, 300], [0, 0.5774, 0], [-0.5, 0.2887, 60], [-0.5, -0.2887, 120], [0, -0.5774, 180], [0.5, -0.2887, 240]]
    },
    {
      name: 'Home',
      intro: 'Squares and triangles, together at last.',
      hint: 'Squares build the walls, triangles build the roof.',
      container: loosen([[-1, roofY + 2], [1, roofY + 2], [1, roofY], [0, roofY - 2 * H], [-1, roofY]], 1.004),
      pieces: pieces(4, 4),
      scramble: true,
      solution: [[-0.5, 0.366, 0], [0.5, 0.366, 0], [-0.5, 1.366, 0], [0.5, 1.366, 0], [0, -1.2887, 0], [-0.5, -0.4226, 0], [0.5, -0.4226, 0], [0, -0.7113, 180]]
    },
    {
      name: 'Lantern',
      intro: 'A honeycomb, stretched, with two squares across the middle.',
      hint: 'Two squares side by side across the middle. Three triangles above them and three below: point, flip, point.',
      container: loosen([[-1, -0.5], [-0.5, -0.5 - H], [0.5, -0.5 - H], [1, -0.5], [1, 0.5], [0.5, 0.5 + H], [-0.5, 0.5 + H], [-1, 0.5]], 1.004),
      pieces: pieces(2, 6),
      scramble: true,
      solution: [[-0.5, 0, 0], [0.5, 0, 0], [-0.5, -0.7887, 0], [0.5, -0.7887, 0], [0, -1.0774, 180], [-0.5, 0.7887, 180], [0.5, 0.7887, 180], [0, 1.0774, 0]]
    },
    {
      name: 'Tilt',
      intro: 'One triangle. One box. The box is narrower than the triangle.',
      hint: 'Lean it 15° and tuck one corner of the triangle into a corner of the box.',
      container: box(0.972),
      pieces: pieces(0, 1),
      solution: [[0.0717, 0.0717, 15]]
    },
    {
      name: 'Squeeze',
      intro: 'Three shapes. Side by side they would need a bigger box.',
      hint: 'Nothing leans. The square sits against the middle of one wall. One triangle rests flat on the floor, the other hangs flat from the ceiling, and their points meet beside the square.',
      container: box(1.783),
      pieces: pieces(1, 2),
      solution: [[0.388, 0, 0], [-0.388, 0.599, 0], [-0.388, -0.599, 180]]
    },
    {
      name: 'Five Alive',
      intro: 'Five squares in a box too small for a tidy grid.',
      hint: 'One square in each corner. The fifth sits in the middle, turned 45°.',
      fact: 'The smallest box that holds five unit squares has side 2 + 1/√2 ≈ 2.707. This one is 2.713.',
      container: box(2.713),
      pieces: pieces(5, 0),
      solution: [[-0.8565, -0.8565, 0], [0.8565, -0.8565, 0], [-0.8565, 0.8565, 0], [0.8565, 0.8565, 0], [0, 0, 45]]
    },
    {
      name: 'Dozen',
      intro: 'Twelve sides, eighteen shapes, no gaps.',
      hint: 'Six triangles make a hexagon in the middle. Put a square on each of its sides, then a triangle in every gap. Everything sits on a multiple of 30°.',
      container: loosen(ngon(12, 1 / (2 * Math.sin(Math.PI / 12)), 15), 1.004),
      pieces: pieces(6, 12),
      scramble: true,
      solution: [[1.183, 0.683, 30], [0, 1.366, 0], [-1.183, 0.683, 60], [-1.183, -0.683, 30], [0, -1.366, 0], [1.183, -0.683, 60], [0.5, 0.2887, 300], [0, 0.5774, 0], [-0.5, 0.2887, 60], [-0.5, -0.2887, 120], [0, -0.5774, 180], [0.5, -0.2887, 240], [1.5774, 0, 270], [0.7887, 1.366, 330], [-0.7887, 1.366, 30], [-1.5774, 0, 90], [-0.7887, -1.366, 150], [0.7887, -1.366, 210]]
    },
    {
      name: 'Diamond',
      intro: 'Two triangles, and a box that looks too small for them.',
      hint: 'Join them edge to edge to make a diamond. Then lay the diamond corner to corner across the box: one triangle at 15°, the other at 75°.',
      fact: 'The diamond is \u221A3 long, so it only fits along the diagonal. The smallest box is \u221A6/2 \u2248 1.225 across; this one is 1.232.',
      container: box(1.232),
      pieces: pieces(0, 2),
      solution: [[0.204, 0.204, 15], [-0.204, -0.204, 75]]
    },
    {
      name: 'Odd Couple',
      intro: 'One square, one triangle. Stacked up they would poke out of the top.',
      hint: 'The square goes snug in a corner. The triangle goes in the opposite corner, turned to 75°, so one of its edges slants across the square\u2019s free corner.',
      container: box(1.619),
      pieces: pieces(1, 1),
      solution: [[0.3095, 0.3095, 0], [-0.4013, -0.388, 75]]
    },
    {
      name: 'Tripod',
      intro: 'A triangle with barely room for two squares side by side. Fit three.',
      hint: 'Give each square its own wall. One sits flat on the floor, and the other two lie flat against the sloping sides, at 30° and 60°.',
      container: loosen([[0, -2 * H / 3], [0.5, H / 3], [-0.5, H / 3]], 3.245),
      pieces: pieces(3, 0),
      solution: [[0.6482, 0.2493, 60], [-0.1057, -0.6905, 30], [-0.5387, 0.4255, 0]]
    },
    {
      name: 'Pinwheel',
      intro: 'Three squares in a honeycomb cell. A neat row will not fit.',
      hint: 'Each square lies flat against a wall, with an empty wall between each pair. They sit at 0°, 30° and 60°, like the blades of a pinwheel.',
      container: ngon(6, 1.372, 0),
      pieces: pieces(3, 0),
      solution: [[-0.1895, 0.6822, 0], [-0.503, -0.5052, 30], [0.6795, -0.1872, 60]]
    },
    {
      name: 'Trio',
      intro: 'Three triangles, and a box that only looks big enough for two.',
      hint: 'One triangle hangs flat from the ceiling, at 60°. One stands flat against the right-hand wall, at 30°. The third tucks into the bottom-left corner at 105°.',
      container: box(1.488),
      pieces: pieces(0, 3),
      solution: [[-0.1412, -0.4553, 60], [0.4361, 0.122, 30], [-0.3358, 0.3358, 105]]
    },
    {
      name: 'Ten Tight',
      intro: 'Ten squares. A 4×4 box would be easy, so this one is smaller.',
      hint: 'Three squares in one corner, three in the opposite corner, one in each of the other two. The last two turn 45° and run down the diagonal.',
      fact: 'Best possible is 3 + 1/√2 ≈ 3.707, found by Frits Göbel in 1979 and proved in 2003. This box is 3.713.',
      container: box(3.713),
      pieces: pieces(10, 0),
      solution: [[-1.3565, -1.3565, 0], [-0.3565, -1.3565, 0], [-1.3565, -0.3565, 0], [1.3565, 1.3565, 0], [0.3565, 1.3565, 0], [1.3565, 0.3565, 0], [1.3565, -1.3565, 0], [-1.3565, 1.3565, 0], [-0.2071, 0.2012, 45], [0.5, -0.5059, 45]]
    },
    {
      name: 'Eleven',
      intro: 'One more square, and the neat patterns stop working.',
      hint: 'Six squares stay straight: one in each of two neighbouring corners, an L of three in a third corner, and one more further along that wall. The other five lean 40° in a clump.',
      fact: 'Walter Trump found this packing in 1979. The record box is 3.8771 across; this one is 3.885.',
      container: box(3.885),
      pieces: pieces(11, 0),
      solution: [[-1.4431, -1.443, 0], [1.4431, -1.4432, 0], [-1.4425, 1.4425, 0], [-0.4425, 1.4425, 0], [-1.4425, 0.4425, 0], [0.5575, 1.4436, 0], [-0.675, -0.4857, 40], [0.0212, 0.2403, 40], [1.2381, 0.4424, 40], [0.7116, -0.4858, 40], [0.0154, -1.2118, 40]]
    },
    {
      name: 'Seventeen',
      intro: 'The famously ugly one, and yes, it is hard. Pack it and a prize ships to you.',
      hint: 'Ten squares stay straight: an L of three in each bottom corner, one in each top corner, one on the top wall and one on a side wall. Six lean 40° in a 2\u00D73 block through the middle. The last one leans 37° the other way, tucked in near the top on that same side.',
      fact: 'John Bidwell found this packing in 1998. Nobody has beaten it, and nobody has proved it is the best. His box is 4.6755 across; this one is 4.68.',
      container: box(4.68),
      pieces: pieces(17, 0),
      solution: [[-1.84, 1.8406, 0], [-0.84, 1.84, 0], [-1.8405, 0.8412, 0], [1.84, 1.84, 0], [0.84, 1.84, 0], [1.84, 0.84, 0], [-1.8401, -1.8401, 0], [1.8406, -1.8405, 0], [0.0628, -1.84, 0], [1.84, -0.16, 0], [-0.9056, -1.0803, 40], [-1.6074, -0.3638, 40], [-0.0561, -0.5373, 40], [-0.6953, 0.2308, 40], [0.6356, 0.2005, 40], [-0.0026, 0.9704, 40], [0.9613, -1.0143, 323]]
    },
    {
      name: 'Brickwork',
      bonus: true,
      intro: 'No powers here. Four bricks, a square, and a box three across.',
      hint: 'The square goes dead centre. The four bricks chase each other round it, each one lying along a different wall.',
      container: box(3.006),
      pieces: pieces(1, 0, 4),
      solution: [[0, 0, 0], [-0.5, -1, 0], [1, -0.5, 90], [0.5, 1, 0], [-1, 0.5, 90]]
    },
    {
      name: 'Corners',
      bonus: true,
      intro: 'A hexagon and three triangles. The hexagon takes up most of the room.',
      hint: 'The hexagon sits in the middle with three of its sides against the walls. A triangle fills each corner.',
      container: loosen([[0, -2 * H / 3], [0.5, H / 3], [-0.5, H / 3]], 3.012),
      pieces: pieces(0, 3, 0, 1),
      solution: [[0, -1.1547, 0], [-1, 0.5774, 0], [1, 0.5774, 0], [0, 0, 0]]
    },
    {
      name: 'Wedged',
      bonus: true,
      intro: 'One hexagon. It is two across, and the box is not.',
      hint: 'Turn it 15°. Two of its corners touch the side walls and two touch the floor and ceiling.',
      fact: 'The smallest square that holds a hexagon of side 1 is 2 cos 15° \u2248 1.932 across. This one is 1.94.',
      container: box(1.94),
      pieces: pieces(0, 0, 0, 1),
      solution: [[0, 0, 15]]
    },
    {
      name: 'Snug',
      bonus: true,
      intro: 'A hexagon and two triangles, in a box that fits them like a glove.',
      hint: 'Stand the hexagon on a point, at 30°, against the right-hand wall. Its sloping sides leave a notch at the top and the bottom on the left. One triangle goes in the bottom corner at 90°, pointing at the hexagon, and the other in the top corner at 75°.',
      container: box(2.321),
      pieces: pieces(0, 2, 0, 1),
      solution: [[-0.8281, 0.6605, 90], [-0.7523, -0.7523, 75], [0.2945, -0.0247, 30]]
    },
    {
      name: 'Trefoil',
      bonus: true,
      intro: 'A tiling: three hexagons and six triangles fill this hexagon with nothing left over.',
      hint: 'No hexagon goes in the middle. All three meet at the centre point, like a three-leaf clover, each one reaching out to a wall. That leaves three empty corners, and each takes a pair of triangles.',
      fact: 'A hexagon of side 2 is exactly 24 small triangles. Three hexagons use 18 of them, and the six loose triangles are the rest.',
      container: loosen(ngon(6, 2, 0), 1.004),
      pieces: pieces(0, 6, 0, 3),
      solution: [[-1.5, 0.2887, 180], [-1.5, -0.2887, 0], [0.5, 1.4434, 0], [1, 1.1547, 180], [0.5, -1.4434, 180], [1, -1.1547, 0], [1, 0, 0], [-0.5, 0.866, 0], [-0.5, -0.866, 0]]
    },
    {
      name: 'Bricked In',
      bonus: true,
      intro: 'Two bricks, and a hexagon that looks a size too small.',
      hint: 'Lay the bricks side by side to make a block, then turn the whole block to 15°. Its four corners each find a different wall.',
      container: ngon(6, 1.547, 0),
      pieces: pieces(0, 0, 2),
      solution: [[-0.02, 0.5235, 15], [0.0088, -0.5041, 15]]
    },
    {
      name: 'Twin Hex',
      bonus: true,
      intro: 'Two hexagons. Side by side they are four across; stacked they are too tall.',
      hint: 'Turn both to 15°. Put one in the top-left corner and the other in the bottom-right, so they meet along a slanted edge in the middle.',
      container: box(3.17),
      pieces: pieces(0, 0, 0, 2),
      solution: [[-0.6191, -0.6191, 15], [0.6191, 0.5923, 15]]
    },
    {
      name: 'Off Centre',
      bonus: true,
      intro: 'A hexagon inside a hexagon, with two triangles to squeeze in beside it.',
      hint: 'Keep the hexagon straight but push it into the top-left, off centre. That opens a crescent of room on the other side: one triangle goes on the right at 105°, the other at the bottom at 15°.',
      container: ngon(6, 1.487, 0),
      pieces: pieces(0, 2, 0, 1),
      solution: [[0.9293, -0.1494, 105], [0.3702, 0.8113, 15], [-0.3425, -0.2502, 0]]
    },
    {
      name: 'Rosette',
      bonus: true,
      intro: 'The big tiling: one hexagon, six squares and six triangles make a perfect twelve-sided ring.',
      hint: 'The hexagon goes dead centre. A square sits flat against each of its six sides. The six gaps between the squares are each exactly one triangle, point inwards.',
      fact: 'This is one patch of a pattern that can tile a whole floor: every corner is where a triangle, two squares and a hexagon meet.',
      container: loosen(ngon(12, 1.9318517, 15), 1.004),
      pieces: pieces(6, 6, 0, 1),
      solution: [[1.183, 0.683, 30], [0, 1.366, 0], [-1.183, 0.683, 60], [-1.183, -0.683, 30], [0, -1.366, 0], [1.183, -0.683, 60], [1.5774, 0, 30], [0.7887, 1.366, 90], [-0.7887, 1.366, 30], [-1.5774, 0, 90], [-0.7887, -1.366, 30], [0.7887, -1.366, 90], [0, 0, 0]]
    },
    {
      name: 'Warm Up',
      powers: 1,
      intro: 'A new shape, the brick, two squares long. And some shapes have powers now: pick one up to see.',
      hint: 'The brick lies along one wall. The two squares sit side by side along the other.',
      container: box(2.004),
      pieces: pieces(2, 0, 1),
      solution: [[-0.5, 0.5, 0], [0.5, 0.5, 0], [0, -0.5, 0]]
    },
    {
      name: 'Boat',
      powers: 1,
      intro: 'Five triangles in a hull.',
      hint: 'Three stand on the floor. The other two hang upside-down between them.',
      container: loosen([[-1.5, H / 2], [1.5, H / 2], [1, -H / 2], [-1, -H / 2]], 1.004),
      pieces: pieces(0, 5),
      solution: [[-1, 0.1443, 0], [0, 0.1443, 0], [1, 0.1443, 0], [-0.5, -0.1443, 180], [0.5, -0.1443, 180]]
    },
    {
      name: 'Shelf',
      powers: 1,
      intro: 'Two bricks, two squares, two rows.',
      hint: 'Each row is one brick and one square. Put the squares at opposite ends.',
      container: loosen(rect(3, 2), 1.002),
      pieces: pieces(2, 0, 2),
      solution: [[1, -0.5, 0], [-1, 0.5, 0], [-0.5, -0.5, 0], [0.5, 0.5, 0]]
    },
    {
      name: 'Slant',
      powers: 1,
      intro: 'A leaning box, two triangles, and another new shape: the hexagon.',
      hint: 'The hexagon goes in the middle and touches all four walls. A triangle fills each sharp corner.',
      container: loosen([[-1.5, -H], [0.5, -H], [1.5, H], [-0.5, H]], 1.004),
      pieces: pieces(0, 2, 0, 1),
      solution: [[-1, -0.5774, 180], [1, 0.5774, 0], [0, 0, 0]]
    },
    {
      name: 'Barge',
      powers: 2,
      intro: 'Two powers at once from here.',
      hint: 'Push the hexagon into the top-left corner, flat against the ceiling and the floor. Two triangles fit beside it at the top, four along the floor.',
      container: loosen([[-1, -H], [1, -H], [2, H], [-2, H]], 1.004),
      pieces: pieces(0, 6, 0, 1),
      scramble: true,
      solution: [[0.5, -0.5774, 180], [1, -0.2887, 0], [-1.5, 0.5774, 0], [0.5, 0.5774, 0], [1, 0.2887, 180], [1.5, 0.5774, 0], [-0.5, 0, 0]]
    },
    {
      name: 'Windmill',
      powers: 1,
      sure: ['sleeper'],
      intro: 'No more neat grids. Four triangles, and a box that looks one too small.',
      hint: 'A pinwheel. Each triangle lies with one side flat against a different wall, pushed along to one end of it, all four going the same way round.',
      container: box(1.584),
      pieces: pieces(0, 4),
      solution: [[0.2876, 0.5003, 0], [-0.2876, -0.5003, 60], [0.5003, -0.2876, 30], [-0.5003, 0.2876, 90]]
    },
    {
      name: 'Odd Squad',
      powers: 2,
      intro: 'A square and three triangles, in a box with no room to line them up.',
      hint: 'The square goes snug in a corner. One triangle hangs upside-down beneath it. One lies with a side flat against the wall beside the square, at 30°. The last goes in the far corner, turned to 105°.',
      container: box(1.872),
      pieces: pieces(1, 3),
      solution: [[-0.4331, -0.4331, 0], [-0.4147, 0.3557, 60], [0.3754, 0.4147, 105], [0.6442, -0.4147, 30]]
    },
    {
      name: 'Corner Brick',
      powers: 2,
      sure: ['chameleon'],
      chameleon: 3,   // the brick
      masked: 'Give each square a corner of its own. The chameleon gets whatever room is left, and it will not go in straight.',
      intro: 'Three squares and a brick. The box is well short of three across.',
      hint: 'A square goes snug in each of three corners. The brick turns 45° and lies along the diagonal, with its end pushed into the empty corner.',
      container: box(2.775),
      pieces: pieces(3, 0, 1),
      solution: [[0.8526, 0.8526, 0], [0.8844, -0.8844, 0], [-0.8844, -0.8844, 0], [-0.3237, 0.3218, 135]]
    },
    {
      name: 'Rough Diamond',
      powers: 2,
      intro: 'Three squares, two triangles, and not much more room than the squares need.',
      hint: 'The three squares make an L round one corner. The two triangles share the opposite corner, joined edge to edge as a diamond laid across the diagonal: one at 15°, the other at 75°.',
      container: box(2.185),
      pieces: pieces(3, 2),
      solution: [[-0.4104, -0.5896, 0], [0.5896, -0.5896, 0], [0.5846, 0.4104, 0], [-0.6814, 0.2706, 75], [-0.2757, 0.6814, 15]]
    },
    {
      name: 'Crossbar',
      powers: 2,
      intro: 'Two bricks and a square. Laid straight they need a box three across; this one is not.',
      hint: 'One brick stands upright against a side wall, pushed into the top corner. The square sits against the top wall beside it. The second brick turns 45° and lies across the corner that is left.',
      container: box(2.921),
      pieces: pieces(1, 0, 2),
      solution: [[0.0426, -0.9574, 0], [0.3968, 0.3968, 135], [-0.9574, -0.4561, 90]]
    },
    {
      name: 'Hex Mix',
      powers: 3,
      intro: 'Two squares and two triangles in a honeycomb cell. Three powers at once from here.',
      hint: 'One square turns 45° and pokes a corner into a corner of the hexagon. The other lies flat against a wall on the far side, at 60°. One triangle lies flat against a wall next to the first square, and the other fills the gap that is left, at 105°.',
      container: ngon(6, 1.291, 0),
      pieces: pieces(2, 2),
      solution: [[0.5664, -0.0196, 45], [-0.4642, 0.4213, 60], [0.0865, -0.824, 60], [-0.528, -0.4944, 105]]
    },
    {
      name: 'Mixed Bag',
      powers: 3,
      intro: 'One of each: a hexagon, a square and a triangle.',
      hint: 'Turn the hexagon 15° and push it into a corner. The square goes snug in the opposite corner. The triangle squeezes into a third corner at 90°, one side upright against the wall.',
      container: box(2.587),
      pieces: pieces(1, 1, 0, 1),
      solution: [[0.7903, 0.7863, 0], [-0.9024, 0.7903, 90], [-0.3238, -0.3244, 15]]
    },
    {
      name: 'Channel',
      powers: 3,
      intro: 'Two bricks and two triangles, in a box too narrow to lay anything flat.',
      hint: 'Stand a brick upright against each side wall: one pushed up into its top corner, the other down into its bottom corner. The triangles go in the channel between them, one at the top at 45° and one at the bottom at 105°.',
      container: box(2.619),
      pieces: pieces(0, 2, 2),
      solution: [[0.1028, 0.8982, 105], [-0.1018, -0.8982, 45], [0.8065, -0.3064, 90], [-0.8065, 0.3054, 90]]
    },
    {
      name: 'Five Points',
      powers: 3,
      intro: 'Five triangles, and none of them sits square.',
      hint: 'One hangs flat from the middle of the top wall. The other four each have a side standing upright, so they point left or right: one against each side wall, half way up, and two more below them on the floor.',
      container: box(1.812),
      pieces: pieces(0, 5),
      solution: [[0.6141, -0.1037, 30], [0.3254, 0.4028, 90], [-0.3254, 0.4028, 30], [-0.6141, -0.0972, 90], [-0.0019, -0.6141, 60]]
    },
    {
      name: 'Tight Bricks',
      powers: 3,
      sure: ['sticky', 'magnet', 'chameleon'],
      chameleon: 6,   // which shape is the chameleon here: the brick along the top wall
      // the hint with a chameleon about: it says where the chameleon goes, and never what shape it really is
      masked: 'The chameleon sits at the top left, against the top wall, with a square under it. A brick lies along the bottom wall from the right corner, with a square on top of its end. A square goes in each of the other two corners, and the last two squares turn 45° and run down the diagonal.',
      intro: 'Ten Tight again, with some of its squares welded into bricks. And powers.',
      hint: 'A brick lies along the top wall from the left corner, with a square under its end. The other brick lies along the bottom wall from the right corner, with a square on top of its end. A square goes in each of the other two corners, and the last two turn 45° and run down the diagonal.',
      container: box(3.713),
      pieces: pieces(6, 0, 2),
      solution: [[-1.3565, -0.3565, 0], [1.3565, 0.3565, 0], [1.3565, -1.3565, 0], [-1.3565, 1.3565, 0], [-0.2071, 0.2012, 45], [0.5, -0.5059, 45], [-0.8565, -1.3565, 0], [0.8565, 1.3565, 0]]
    },
    // The fourth chapter (twist: true): tight packings, each with one idea of its own, and powers on some of them.
    // pin gives a power to one shape by number. A level may have two boxes (containers); sets of entangled shapes
    // that turn together (twins) or against each other (gears); and a line no entangled shape may cross (divide).
    {
      name: 'Haojun\u2019s Gears',
      twist: true,
      gears: [[0, 1], [2, 3]],   // geared pairs: one turns against the other
      intro: 'Windmill again, in pairs. Shapes that look alike are geared: turn one, and the other turns the opposite way.',
      hint: 'A pinwheel. Each triangle lies with one side flat against a different wall, pushed along to one end of it, all four going the same way round. The two of a pair go against opposite walls, top and bottom or left and right: get one flat against its wall and the other is right too.',
      container: box(1.584),
      pieces: pieces(0, 4),
      solution: [[0.2876, 0.5003, 0], [-0.2876, -0.5003, 60], [0.5003, -0.2876, 30], [-0.5003, 0.2876, 90]]
    },
    {
      name: 'Split Decision',
      twist: true,
      intro: 'Two boxes, two squares, five triangles. Work out which shapes go in which box.',
      hint: 'The smaller box takes a square and two triangles: the square against the middle of the right-hand wall, one triangle flat on the floor and one hanging flat from the ceiling, their points meeting beside it. The bigger box takes the rest: the square snug in the top-left corner, a triangle hanging upside-down beneath it, one flat against the right-hand wall at 30°, and the last in the bottom corner at 105°.',
      containers: [box(1.783).map(function (p) { return [p[0] - 1.086, p[1]]; }), box(1.872).map(function (p) { return [p[0] + 1.0415, p[1]]; })],
      container: box(1.783).map(function (p) { return [p[0] - 1.086, p[1]]; }).concat(box(1.872).map(function (p) { return [p[0] + 1.0415, p[1]]; })),
      pieces: pieces(2, 5),
      solution: [[-0.698, 0, 0], [0.6084, -0.4331, 0], [-1.474, 0.599, 0], [-1.474, -0.599, 180], [0.6268, 0.3557, 60], [1.4169, 0.4147, 105], [1.6857, -0.4147, 30]]
    },
    {
      name: 'Short Fuse',
      twist: true,
      powers: 1,
      sure: ['mine'],
      pin: { mine: 3 },   // one of the bricks
      intro: 'Two bricks and three triangles. One brick is a mine, and neither will go in straight.',
      hint: 'Lay the two bricks side by side as one big square, both turned to 120°, so the big square stands on a corner and touches all four walls. Triangles fill three of the gaps it leaves against the walls. Turn the mine in short goes, outside the box, and its fuse never runs out.',
      container: box(2.74),
      pieces: pieces(0, 3, 2),
      solution: [[0.866, 1.0774, 240], [1.0774, -0.866, 150], [-0.866, -1.0773, 180], [0.433, 0.25, 300], [-0.433, -0.25, 120]]
    },
    {
      name: 'Sleepwalker',
      twist: true,
      powers: 1,
      sure: ['sleeper'],
      pin: { sleeper: 8 },   // the brick
      intro: 'Ten Tight once more, with one brick. The brick is a sleeper, and it will not lie straight.',
      hint: 'Turn the brick to 45° outside the box, then carry it in and lay it corner to corner through the middle. Three squares make an L in one corner beside it, three in the opposite corner, and one goes in each of the other two.',
      container: box(3.713),
      pieces: pieces(8, 0, 1),
      solution: [[-1.3565, -1.3565, 0], [-0.3565, -1.3565, 0], [-1.3565, -0.3565, 0], [1.3565, 1.3565, 0], [0.3565, 1.3565, 0], [1.3565, 0.3565, 0], [1.3565, -1.3565, 0], [-1.3565, 1.3565, 0], [0.1464, -0.1523, 135]]
    },
    {
      name: 'Keystone',
      twist: true,
      powers: 2,
      sure: ['puffer'],
      pin: { puffer: 6 },   // the hexagon
      intro: 'Seven shapes, and the hexagon is a puffer: it goes in first, with nothing to line it up against.',
      hint: 'The hexagon goes in before anything else: turned 15° off straight and pushed into the top-right corner. Two squares stack down the left wall from the top corner, and the third goes in the bottom-right corner. The three triangles fill the bottom-left: one flat on the floor, one above it against the left wall at 60°, and one leaning at 45° between them and the hexagon.',
      container: box(2.944),
      pieces: pieces(3, 3, 0, 1),
      solution: [[0.9677, 0.9681, 0], [-0.9666, 0.0334, 0], [-0.9659, -0.9666, 0], [-0.9685, 0.8281, 300], [0.08, 0.7987, 45], [-0.5048, 1.1798, 120], [0.5025, -0.5025, 15]]
    },
    {
      name: 'Double Bluff',
      twist: true,
      powers: 2,
      sure: ['chameleon', 'magnet'],
      chameleon: 1,   // the triangle on the floor
      masked: 'The chameleon sits on the floor in the bottom-left corner. The brick stands upright against the left wall above it, in the top corner, with the square beside it against the ceiling. The hexagon turns 15° off straight and goes into the bottom-right corner, and a triangle lies in the top-right corner, pointing left.',
      intro: 'One of each, and one more. Counting the shapes will not tell you which.',
      hint: 'The brick stands upright against the left wall, in the top corner, with the square beside it against the ceiling. Turn the hexagon 15° off straight and push it into the bottom-right corner. One triangle lies in the top-right corner, pointing left; the other sits on the floor in the bottom-left.',
      container: box(2.892),
      pieces: pieces(1, 2, 1, 1),
      solution: [[0.0578, -0.9422, 90], [-0.5867, 1.1457, 240], [1.1353, -0.8924, 270], [-0.9422, -0.4422, 90], [0.4763, 0.4763, 105]]
    },
    {
      name: 'Eleven Bricks',
      twist: true,
      powers: 3,
      sure: ['magnet', 'chameleon'],
      chameleon: 7,   // the brick standing against the side wall
      masked: 'The chameleon stands upright against the left wall, in the bottom corner. A brick lies along the floor beside it. A square goes in each top corner, and the other five squares lean 40° in a clump.',
      intro: 'Eleven again, with four of its squares welded into two bricks. And powers.',
      hint: 'One brick stands upright against the left wall, in the bottom corner. The other lies along the floor beside it. A square goes in each top corner, and the other five squares lean 40° in a clump.',
      container: box(3.885),
      pieces: pieces(7, 0, 2),
      solution: [[-1.4431, -1.443, 0], [1.4431, -1.4432, 0], [-0.675, -0.4857, 40], [0.0212, 0.2403, 40], [1.2381, 0.4424, 40], [0.7116, -0.4858, 40], [0.0154, -1.2118, 40], [-1.4425, 0.9425, 90], [0.0575, 1.443, 0]]
    },
    {
      name: 'Duality',
      twist: true,
      powers: 1,
      twins: [[4, 5], [0, 6], [1, 7]],   // entangled pairs: each turns when the other does
      pool: ['mine', 'sticky', 'sleeper', 'magnet', 'puffer'],   // no chameleon: its line would take the place of the one that explains the level
      divide: -0.0155,   // a line half way between the boxes: an entangled shape keeps to the side its spot is on
      intro: 'Two boxes. Shapes that look alike are entangled: turn one and its twin turns too. Neither can cross the line.',
      hint: 'The square box is Five Alive: four squares in the corners and one in the middle at 45°. The honeycomb is Pinwheel: three squares flat against every other wall, at 0°, 30° and 60°. Each pair of twins is split by the line, one in each box. The twin of the square in the middle sits straight in the honeycomb; the twins of the two that lean there sit straight in corners of the square box.',
      containers: [box(2.713).map(function (p) { return [p[0] - 1.522, p[1]]; }), ngon(6, 1.372, 0).map(function (p) { return [p[0] + 1.5065, p[1]]; })],
      container: box(2.713).map(function (p) { return [p[0] - 1.522, p[1]]; }).concat(ngon(6, 1.372, 0).map(function (p) { return [p[0] + 1.5065, p[1]]; })),   // every corner of both, for the board's bounds
      pieces: pieces(8, 0),
      solution: [[-2.3785, -0.8565, 0], [-0.6655, -0.8565, 0], [-2.3785, 0.8565, 0], [-0.6655, 0.8565, 0], [-1.522, 0, 45], [1.317, 0.6822, 0], [1.0035, -0.5052, 30], [2.186, -0.1872, 60]]
    },
    {
      name: 'Trinity',
      twist: true,
      twins: [[2, 3, 1], [0, 5, 4]],   // entangled threes: all turn when one does
      // (the honeycomb is tucked in under the triangle's slope, nearer than the two would stand side by side)
      intro: 'Tripod and Pinwheel, side by side. The squares are entangled in threes: turn one and the other two turn with it.',
      hint: 'Each box takes three squares flat against three walls, at 0°, 30° and 60°. In each set of three, two squares match and the third is 30° off. Put the matching two in different boxes. One set gives both boxes their straight square and the triangle its 30°; the other gives both their 60° and the honeycomb its 30°.',
      containers: [loosen([[0, -2 * H / 3], [0.5, H / 3], [-0.5, H / 3]], 3.245).map(function (p) { return [p[0] - 1.147, p[1] + 0.468]; }), ngon(6, 1.372, 0).map(function (p) { return [p[0] + 1.3975, p[1]]; })],
      container: loosen([[0, -2 * H / 3], [0.5, H / 3], [-0.5, H / 3]], 3.245).map(function (p) { return [p[0] - 1.147, p[1] + 0.468]; }).concat(ngon(6, 1.372, 0).map(function (p) { return [p[0] + 1.3975, p[1]]; })),
      pieces: pieces(6, 0),
      solution: [[-0.4988, 0.7173, 60], [-1.2527, -0.2225, 30], [-1.6857, 0.8935, 0], [1.208, 0.6822, 0], [0.8945, -0.5052, 30], [2.077, -0.1872, 60]]
    }
  ];
})();

// ---------------------------------------------------------------------------
// The leaderboard itself. Everything above this line is the game's own
// geom.js and levels.js, pasted in by packman/tools/build-worker.py so a
// score can be checked here with the very code that judges it in the game.
// ---------------------------------------------------------------------------

const G = PackmanGeom, LEVELS = PackmanLevels;
const BY_NAME = new Map(LEVELS.map((l) => [l.name, l]));
const NAMES = LEVELS.map((l) => l.name);
const TOP = 10;            // rows returned for a board, unless more are asked for
const MOST = 100;          // and the most that can be
const PER_HOUR = 60;       // scores one address may send in an hour
const BLOCKED = /fuck|shit|cunt|nigg|fag|bitch|whore|rape|nazi|hitler|porn|penis|vagina/i;

const CORS = {
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Methods": "GET, POST, DELETE, OPTIONS",
	"Access-Control-Allow-Headers": "Content-Type",
	"Content-Type": "application/json",
};
const json = (body, status = 200, extra = {}) =>
	new Response(JSON.stringify(body), { status, headers: { ...CORS, ...extra } });

// The same hash the game uses to pick a player's block and animal name from
// their id, so nobody chooses their own picture.
function hash(s) {
	let h = 2166136261;
	for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); }
	return h >>> 0;
}

function cleanName(s) {
	return String(s || "").replace(/[\u0000-\u001f\u007f<>&"'`\\]/g, "").replace(/\s+/g, " ").trim().slice(0, 18);
}

// Is this really a packing of that level? The level's own pieces, put where
// the player left them, judged by the game's rules.
function packed(level, spots) {
	if (!Array.isArray(spots) || spots.length !== level.pieces.length) return false;
	const pieces = [];
	for (let i = 0; i < spots.length; i++) {
		const s = spots[i];
		if (!Array.isArray(s) || s.length !== 3 || !s.every((v) => typeof v === "number" && isFinite(v) && Math.abs(v) < 1e4)) return false;
		pieces.push({ type: level.pieces[i], size: 1, x: s[0], y: s[1], angle: s[2] });
	}
	// (a level with two boxes lists them as containers; its shapes are judged each by the box it is in)
	return G.evaluate(pieces, level.containers ? G.makeBoxes(level.containers) : G.makeContainer(level.container)).solved;
}

let ready = false;
async function tables(db) {
	if (ready) return;
	await db.batch([
		db.prepare("CREATE TABLE IF NOT EXISTS scores (level TEXT NOT NULL, pid TEXT NOT NULL, name TEXT NOT NULL, t REAL NOT NULL, m INTEGER NOT NULL, at INTEGER NOT NULL, PRIMARY KEY (level, pid))"),
		db.prepare("CREATE INDEX IF NOT EXISTS scores_rank ON scores (level, t, m, at)"),
		db.prepare("CREATE TABLE IF NOT EXISTS rate (k TEXT PRIMARY KEY, n INTEGER NOT NULL, exp INTEGER NOT NULL)"),
	]);
	ready = true;
}

// One board. A player's line is everything they have packed: how many levels,
// and the moves and time those took at their best. More levels ranks higher;
// then fewer moves; then less time.
const row = (r) => ({ name: r.name, n: r.n, m: r.m, t: Math.round(r.t * 10) / 10, a: hash(r.pid) });
const TOTALS = `SELECT pid, MAX(name) AS name, COUNT(*) AS n, SUM(m) AS m, SUM(t) AS t FROM scores
	WHERE level IN (${NAMES.map(() => "?").join(",")}) GROUP BY pid`;

async function board(db, pid, rows = TOP) {
	const top = await db.prepare(`${TOTALS} ORDER BY n DESC, m, t LIMIT ${rows}`).bind(...NAMES).all();
	const all = await db.prepare(`SELECT COUNT(*) AS c FROM (${TOTALS})`).bind(...NAMES).first();
	const out = { top: top.results.map(row), of: all ? all.c : 0, levels: NAMES.length };
	if (!pid) return out;
	// where the one asking stands, for when they are further down than the top few
	const mine = await db.prepare(`SELECT * FROM (${TOTALS}) WHERE pid = ?`).bind(...NAMES, pid).first();
	if (mine) {
		const ahead = await db.prepare(
			`SELECT COUNT(*) AS c FROM (${TOTALS}) WHERE n > ? OR (n = ? AND (m < ? OR (m = ? AND t < ?)))`
		).bind(...NAMES, mine.n, mine.n, mine.m, mine.m, mine.t).first();
		out.mine = row(mine); out.rank = ahead.c + 1;
	}
	return out;
}

async function tooMany(db, request) {
	const ip = request.headers.get("CF-Connecting-IP") || "?";
	const hour = Math.floor(Date.now() / 3600000);
	// the address is never stored, only a hash of it with the hour
	const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(ip + "|" + hour));
	const k = Array.from(new Uint8Array(bytes).slice(0, 12), (b) => b.toString(16).padStart(2, "0")).join("");
	const r = await db.prepare(
		"INSERT INTO rate (k, n, exp) VALUES (?, 1, ?) ON CONFLICT (k) DO UPDATE SET n = n + 1 RETURNING n"
	).bind(k, (hour + 2) * 3600).first();
	if (r && r.n === 1 && Math.random() < 0.05) await db.prepare("DELETE FROM rate WHERE exp < ?").bind(Math.floor(Date.now() / 1000)).run();
	return r && r.n > PER_HOUR;
}

async function submit(db, request) {
	let b;
	try { b = await request.json(); } catch (e) { return json({ error: "body" }, 400); }
	const level = BY_NAME.get(b && b.level);
	if (!level) return json({ error: "level" }, 400);
	const pid = String(b.pid || "");
	if (!/^[A-Za-z0-9-]{16,48}$/.test(pid)) return json({ error: "pid" }, 400);
	const name = cleanName(b.name);
	if (!name || BLOCKED.test(name.replace(/[^a-z]/gi, ""))) return json({ error: "name" }, 400);
	const t = Math.round(Number(b.t) * 10) / 10, m = Math.round(Number(b.m));
	// every piece has to be moved at least once, and nobody does that in under half a second each
	const n = level.pieces.length;
	if (!isFinite(t) || !isFinite(m) || m < n || m > 100000 || t < n * 0.5 || t > 86400) return json({ error: "score" }, 400);
	// A level with powers is taken on trust: a ghost shares a space, and a chameleon is not
	// always the shape the level lists, so the plain rules cannot judge where its shapes ended up.
	if (!level.powers && !packed(level, b.p)) return json({ error: "unpacked" }, 400);
	if (await tooMany(db, request)) return json({ error: "slow down" }, 429);

	const now = Math.floor(Date.now() / 1000);
	await db.batch([
		// a player has one row a level, and it only ever gets better: fewer moves, or the same in less time
		db.prepare(
			"INSERT INTO scores (level, pid, name, t, m, at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (level, pid) DO UPDATE SET t = excluded.t, m = excluded.m, at = excluded.at WHERE excluded.m < scores.m OR (excluded.m = scores.m AND excluded.t < scores.t)"
		).bind(level.name, pid, name, t, m, now),
		db.prepare("UPDATE scores SET name = ? WHERE pid = ?").bind(name, pid),
	]);
	return json(await board(db, pid));
}

export default {
	async fetch(request, env) {
		if (request.method === "OPTIONS") return new Response(null, { headers: CORS });
		const db = env.DB || env.db;   // the binding's name, in either case
		if (!db) return json({ error: "no database bound as DB" }, 500);
		try {
			await tables(db);
			if (request.method === "POST") return await submit(db, request);
			const query = new URL(request.url).searchParams, pid = query.get("pid") || "";
			if (pid && !/^[A-Za-z0-9-]{16,48}$/.test(pid)) return json({ error: "pid" }, 400);
			if (request.method === "DELETE") {
				// A player takes their own line off the board. The id is the only key to it, and only their browser has it.
				if (!pid) return json({ error: "pid" }, 400);
				const gone = await db.prepare("DELETE FROM scores WHERE pid = ?").bind(pid).run();
				return json({ gone: gone.meta ? gone.meta.changes : 0 });
			}
			if (request.method !== "GET") return json({ error: "method" }, 405);
			const rows = Math.min(MOST, Math.max(1, Math.floor(Number(query.get("top")) || TOP)));
			return json(await board(db, pid, rows), 200, { "Cache-Control": pid ? "no-store" : "public, max-age=20" });
		} catch (err) {
			return json({ error: "exception", detail: String(err) }, 500);
		}
	},
};
