#!/usr/bin/env python3
"""Builds the Packman leaderboard worker: one file to paste into Cloudflare.

The worker checks every score with the game's own geometry and levels, so
those two files are copied into it. Run this again, and redeploy the worker,
whenever packman/geom.js or packman/levels.js changes:

    python3 tools/build-packman-worker.py
"""
import os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
read = lambda p: open(os.path.join(root, p), encoding="utf-8").read().rstrip("\n")

head = """// Cloudflare Worker — the Packman leaderboard.
//
// GENERATED by tools/build-packman-worker.py from packman/geom.js,
// packman/levels.js and packman-scores.src.js. Edit those, not this file.
//
// GET  /api/packman?level=<level name>   the ten fastest for one level
// GET  /api/packman?level=all            the ten fastest across all seventeen
// POST /api/packman                      {level, pid, name, t, m, p} one win; p is where every piece ended up
//
// Deploy via the Cloudflare dashboard:
//   1. Storage & databases -> D1 -> Create database (name: packman).
//   2. Workers & Pages -> Create -> Worker (name: packman-scores) -> Edit code -> paste this file -> Deploy.
//   3. That worker -> Settings -> Bindings -> Add -> D1 database: variable name DB, database packman.
//   4. That worker -> Settings -> Domains & Routes -> Add route: www.garvitgupta.com/api/packman*
// The tables make themselves on the first request.
//
// Housekeeping, from the D1 console:
//   SELECT * FROM scores ORDER BY at DESC LIMIT 50;      -- the latest scores
//   DELETE FROM scores WHERE name = 'someone';           -- take a player off the board
"""

out = "\n\n".join([head.rstrip("\n"), read("packman/geom.js"), read("packman/levels.js"), read("extras/cloudflare-worker/packman-scores.src.js")]) + "\n"
dest = os.path.join(root, "extras/cloudflare-worker/packman-scores.js")
open(dest, "w", encoding="utf-8").write(out)
print("wrote", os.path.relpath(dest, root), len(out), "bytes")
